# Generated by Django 5.1.5 on 2025-03-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
