# Generated by Django 5.1.5 on 2026-05-29 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_backfill_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('PAYROLL', 'Payroll Records'), ('LEAVE', 'Leave Records'), ('DISCIPLINARY', 'Disciplinary Records'), ('AUDIT', 'Audit Trail'), ('TAX', 'Tax Records'), ('INVENTORY', 'Inventory Records')], max_length=50)),
                ('retention_days', models.PositiveIntegerField(default=2555)),
                ('auto_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='company.company')),
            ],
            options={
                'ordering': ['company', 'record_type'],
                'constraints': [models.UniqueConstraint(fields=('company', 'record_type'), name='uniq_retention_company_type')],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('policy_version', models.CharField(default='1.0', max_length=40)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'policy_name', 'policy_version'), name='uniq_acknowledgment_user_policy_version')],
            },
        ),
    ]
