# Generated by Django 5.1.5 on 2026-02-27 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0003_backfill_memberships"),
        ("payroll", "0046_iou_repayment_deduction_percentage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StandupTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKDAYS", "Weekdays"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="WEEKDAYS",
                        max_length=20,
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(default="Africa/Lagos", max_length=64),
                ),
                ("reminder_time", models.TimeField(blank=True, null=True)),
                ("deadline_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standup_teams",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StandupQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=255)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[("TEXT", "Short Text"), ("LONG_TEXT", "Long Text")],
                        default="LONG_TEXT",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="standup.standupteam",
                    ),
                ),
            ],
            options={
                "ordering": ["team", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StandupFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standup_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="standup.standupteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandupCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("MISSED", "Missed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("blocker_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standup_checkins",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_standup_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standup_checkins",
                        to="payroll.employeeprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="standup.standupteam",
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StandupTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("MEMBER", "Member"), ("LEAD", "Lead")],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standup_memberships",
                        to="payroll.employeeprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="standup.standupteam",
                    ),
                ),
            ],
            options={
                "ordering": ["team__name", "employee__first_name"],
            },
        ),
        migrations.CreateModel(
            name="StandupAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("is_blocker", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="standup.standupcheckin",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="standup.standupquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question__order", "id"],
                "indexes": [
                    models.Index(
                        fields=["checkin", "is_blocker"],
                        name="standup_sta_checkin_8b8083_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("checkin", "question"),
                        name="uniq_standup_answer_per_question",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="standupteam",
            index=models.Index(
                fields=["company", "is_active"], name="standup_sta_company_c84700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standupteam",
            index=models.Index(
                fields=["company", "name"], name="standup_sta_company_bc2536_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="standupteam",
            constraint=models.UniqueConstraint(
                fields=("company", "slug"), name="uniq_standup_team_slug_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="standupteam",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uniq_standup_team_name_per_company"
            ),
        ),
        migrations.AddIndex(
            model_name="standupquestion",
            index=models.Index(
                fields=["team", "is_active"], name="standup_sta_team_id_4e6a98_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="standupquestion",
            constraint=models.UniqueConstraint(
                fields=("team", "order"), name="uniq_standup_question_order_per_team"
            ),
        ),
        migrations.AddIndex(
            model_name="standupfollow",
            index=models.Index(
                fields=["team", "follower"], name="standup_sta_team_id_36a72f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="standupfollow",
            constraint=models.UniqueConstraint(
                fields=("team", "follower"), name="uniq_standup_follower_per_team"
            ),
        ),
        migrations.AddIndex(
            model_name="standupcheckin",
            index=models.Index(
                fields=["company", "work_date"], name="standup_sta_company_c1f689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standupcheckin",
            index=models.Index(
                fields=["team", "work_date"], name="standup_sta_team_id_1f2cdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standupcheckin",
            index=models.Index(
                fields=["member", "work_date"], name="standup_sta_member__29bdaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standupcheckin",
            index=models.Index(
                fields=["company", "status", "-work_date"],
                name="standup_sta_company_78f0c1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="standupcheckin",
            constraint=models.UniqueConstraint(
                fields=("team", "member", "work_date"),
                name="uniq_standup_checkin_member_per_day",
            ),
        ),
        migrations.AddIndex(
            model_name="standupteammember",
            index=models.Index(
                fields=["team", "is_active"], name="standup_sta_team_id_c1c3a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standupteammember",
            index=models.Index(
                fields=["employee", "is_active"], name="standup_sta_employe_7a167b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="standupteammember",
            constraint=models.UniqueConstraint(
                fields=("team", "employee"), name="uniq_standup_team_member"
            ),
        ),
    ]
