# Generated by Django 5.1.5 on 2026-02-27 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandupDispatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REMINDER", "Reminder"),
                            ("MISSED", "Mark Missed"),
                            ("DAILY_DIGEST", "Daily Digest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_logs",
                        to="standup.standupteam",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "work_date", "event_type"],
                        name="standup_sta_team_id_4b19a9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "work_date", "event_type"),
                        name="uniq_standup_dispatch_per_event_date",
                    )
                ],
            },
        ),
    ]
