# Generated by Django 4.0.2 on 2022-09-24 18:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import employee.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default=employee.generator.emp_id, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('nin', models.CharField(default=employee.generator.nin_no, editable=False, max_length=255, unique=True)),
                ('tin_no', models.CharField(default=employee.generator.tin_no, editable=False, max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_employment', models.DateField(null=True)),
                ('contract_type', models.CharField(choices=[('P', 'Permanent'), ('T', 'Temporary')], max_length=1, null=True)),
                ('phone', models.CharField(default=1234567890, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{3}\\d{9,15}$')], verbose_name='phone number')),
                ('gender', models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], default='others', max_length=255, verbose_name='gender')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(choices=[('C', 'Casual'), ('JS', 'Junior staff'), ('OP', 'Operator'), ('SU', 'SUpervisor'), ('M', 'Manager'), ('COO', 'C.O.O')], default='casual', max_length=255, verbose_name='designation')),
                ('bank', models.CharField(choices=[('Zenith', 'Zenith BANK'), ('Access', 'Access Bank'), ('GTB', 'GT Bank'), ('Jaiz', 'JAIZ Bank'), ('FCMB', 'FCMB'), ('FBN', 'First Bank'), ('Union', 'Union Bank'), ('UBA', 'UBA')], default='Z', max_length=10, verbose_name='employee BANK')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Bank Account Name')),
                ('bank_account_number', models.CharField(max_length=10, unique=True, verbose_name='Bank Account Number')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
