# Generated by Django 5.1.5 on 2026-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_leadinquiry_workflow_and_marketingevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("website", models.URLField(blank=True)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("local", "Local (Nigeria)"),
                            ("pan_african", "Pan-African"),
                            ("global", "Global"),
                            ("ewa", "EWA / Fintech"),
                            ("eor", "EOR"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("defunct", "Defunct / Collapsed"),
                            ("watch", "Watch"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "pricing_summary",
                    models.TextField(
                        blank=True,
                        help_text="Current published/cited pricing, human-readable.",
                    ),
                ),
                (
                    "pricing_as_of",
                    models.DateField(
                        blank=True,
                        help_text="Date the pricing_summary was last verified.",
                        null=True,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Capability map, e.g. {"statutory_paye": "yes", "ewa": "partial"}. Values: yes / no / partial / unknown.',
                    ),
                ),
                ("positioning_notes", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("last_verified", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Competitor",
                "verbose_name_plural": "Competitors",
                "ordering": ["segment", "name"],
            },
        ),
    ]
