# Generated by Django 5.1.5 on 2026-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_seed_competitors"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "monthly_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per employee per month, billed monthly. Leave blank for custom (Enterprise) pricing.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "annual_monthly_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per employee per month when billed annually (shown on Annual).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "billing_note",
                    models.CharField(
                        blank=True, default="per employee / month", max_length=120
                    ),
                ),
                (
                    "max_employees",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Headcount cap for free/entry tiers; blank means unlimited.",
                        null=True,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Module-gated feature bullets rendered on the pricing page.",
                    ),
                ),
                (
                    "highlight",
                    models.BooleanField(
                        default=False, help_text="Featured plan on the pricing page."
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pricing Plan",
                "verbose_name_plural": "Pricing Plans",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
