"""Domain-specific forms module."""

from decimal import Decimal
from calendar import monthrange
import json

from django import forms
from django.utils import timezone
from django.apps import apps
from django.contrib.auth import get_user_model
from django.db.models import Q

from payroll import models
from monthyear.forms import MonthField
from company.utils import get_user_company
from payroll.forms._helpers import (
    _employee_blocked_for_payday,
    _apply_standard_widget_classes,
    _parse_lines,
    _parse_json_object,
    _normalize_month_widget_data,
    _get_period_bounds,
)

class PayrollForm(forms.Form):
    employee = forms.ModelChoiceField(queryset=models.EmployeeProfile.objects.all())
    basic_salary = forms.DecimalField(max_digits=12, decimal_places=2)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        company = get_user_company(user)
        if company:
            self.fields["employee"].queryset = models.EmployeeProfile.objects.filter(
                company=company
            )
        else:
            self.fields["employee"].queryset = models.EmployeeProfile.objects.none()



class AllowanceForm(forms.ModelForm):
    class Meta:
        model = models.Allowance
        fields = "__all__"



class DeductionForm(forms.ModelForm):
    class Meta:
        model = models.Deduction
        fields = "__all__"


# class CustomMMCF(forms.ModelMultipleChoiceField):
#     def label_from_instance(self, member):
#         return "%s" % member.name



class PayrollRunForm(forms.ModelForm):
    name = forms.CharField(
        label="Pay Period Name",
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control border rounded p-2 w-full"}
        ),
    )
    # slug is auto-generated by AutoSlugField and typically not included in the form directly
    # paydays field will use the default widget from MonthField
    payroll_payday = forms.ModelMultipleChoiceField(
        queryset=models.PayrollEntry.objects.all().order_by("pays__first_name"),
        label="Employee to be included in Payroll for the Month",
        widget=forms.CheckboxSelectMultiple,
        required=False,  # M2M fields are often not required for the initial save
    )
    is_active = forms.BooleanField(label="Is Active?", required=False)
    closed = forms.BooleanField(
        label="Is Closed for Editing?",
        required=False,
        help_text="If checked, this pay period cannot be edited further.",
    )

    class Meta:
        model = models.PayrollRun
        fields = (
            "name",
            # "slug", # Removed as it's auto-generated
            "paydays",
            "payroll_payday",
            "is_active",
            "closed",
        )
        # The MonthField for 'paydays' should render its own widget.
        # You can add custom widgets here if needed for other fields.

        # paydays = forms.DateField( # Removed override
        #     label="Month of Payroll",
        #     widget=forms.TextInput(attrs={"class": "datepicker"}),
        # )

        # forms.ModelMultipleChoiceField(
        #     queryset=models.PayrollEntry.objects.all(),  # Assuming PayrollEntry is the related model
        #     # widget=forms.CheckboxSelectMultiple,  # Use checkboxes for multiple selection
        #     required=False,
        # )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        args, kwargs = _normalize_month_widget_data(args, kwargs, "paydays")
        super().__init__(*args, **kwargs)
        company = get_user_company(self.user)
        if company:
            self.fields["payroll_payday"].queryset = models.PayrollEntry.objects.filter(
                company=company
            ).order_by("pays__first_name")
        else:
            self.fields["payroll_payday"].queryset = models.PayrollEntry.objects.none()

        input_classes = (
            "form-input w-full px-4 py-2.5 border border-secondary-300 rounded-xl "
            "focus:ring-2 focus:ring-primary-500 focus:border-primary-500 text-sm"
        )
        checkbox_classes = (
            "h-4 w-4 text-primary-600 border-secondary-300 rounded focus:ring-primary-500"
        )
        self.fields["name"].widget.attrs["class"] = input_classes
        self.fields["paydays"].widget.attrs["class"] = input_classes
        self.fields["is_active"].widget.attrs["class"] = checkbox_classes
        self.fields["closed"].widget.attrs["class"] = checkbox_classes

    def save(self, commit=True):
        obj = super().save(commit=False)
        requested_closed = bool(self.cleaned_data.get("closed", False))
        is_new = obj.pk is None

        # For newly-created payroll runs, defer closure until after M2M entries
        # are persisted so close-trigger posting can see linked payroll entries.
        if is_new and requested_closed:
            obj.closed = False

        company = get_user_company(self.user)
        if company and not obj.company_id:
            obj.company = company
        if commit:
            obj.save()
            self.save_m2m()
            if is_new and requested_closed:
                obj.closed = True
                obj.save(update_fields=["closed"])
        return obj

    def clean_payroll_payday(self):
        payroll_entries = self.cleaned_data.get("payroll_payday")
        paydays = self.cleaned_data.get("paydays")
        if not payroll_entries or not paydays:
            return payroll_entries

        blocked = []
        for payroll_entry in payroll_entries:
            employee = payroll_entry.pays
            is_blocked, reason = _employee_blocked_for_payday(employee, paydays)
            if is_blocked:
                name = f"{employee.first_name} {employee.last_name}".strip()
                blocked.append(f"{name or employee.emp_id} ({reason})")

        if blocked:
            raise forms.ValidationError(
                "Some selected employees are not payroll-eligible for this period: "
                + ", ".join(blocked)
            )
        return payroll_entries



class MonthForm(forms.Form):
    month = MonthField()



class PayrollRunCreateForm(forms.Form):
    """Enhanced form for creating PayrollRun (Pay Period) with efficient employee selection."""

    name = forms.CharField(
        label="Pay Period Name",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "w-full px-4 py-2.5 border border-secondary-300 rounded-xl focus:ring-2 focus:ring-primary-500 focus:border-primary-500 text-sm",
                "placeholder": "e.g., December 2024 Payroll",
            }
        ),
    )
    paydays = MonthField(
        label="Month",
        required=True,
    )
    is_active = forms.BooleanField(
        label="Mark as Active",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "h-4 w-4 text-primary-600 border-secondary-300 rounded focus:ring-primary-500"
            }
        ),
    )
    closed = forms.BooleanField(
        label="Close for Editing",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "h-4 w-4 text-primary-600 border-secondary-300 rounded focus:ring-primary-500"
            }
        ),
    )

    # Hidden field to store selected employee IDs
    payroll_payday = forms.CharField(
        widget=forms.HiddenInput(attrs={"name": "payroll_payday"}),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        self._selected_employee_ids = []
        args, kwargs = _normalize_month_widget_data(args, kwargs, "paydays")
        super().__init__(*args, **kwargs)

    def clean_payroll_payday(self):
        employee_ids_str = self.cleaned_data.get("payroll_payday", "")
        raw_employee_ids = [
            employee_id.strip()
            for employee_id in employee_ids_str.split(",")
            if employee_id.strip()
        ]
        if not raw_employee_ids:
            raise forms.ValidationError("Select at least one employee for this pay period.")

        employee_ids = []
        for raw_employee_id in raw_employee_ids:
            try:
                employee_ids.append(int(raw_employee_id))
            except (TypeError, ValueError):
                raise forms.ValidationError(
                    "Invalid employee selection. Please refresh the page and try again."
                )

        employee_ids = list(dict.fromkeys(employee_ids))
        company = get_user_company(self.user)
        if not company:
            raise forms.ValidationError(
                "Your active company could not be determined. Please select a company and try again."
            )

        available_employee_ids = set(
            models.EmployeeProfile.objects.filter(
                company=company,
                status="active",
                id__in=employee_ids,
            ).values_list("id", flat=True)
        )
        if available_employee_ids != set(employee_ids):
            raise forms.ValidationError(
                "Selected employees are no longer available for this company. Please refresh the page and try again."
            )

        self._selected_employee_ids = employee_ids
        return ",".join(str(employee_id) for employee_id in employee_ids)

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get("is_active"):
            self.add_error(
                "is_active",
                "Pay period must be marked as active before creation.",
            )
        return cleaned_data

    def save(self):
        """Create PayrollRun instance and related PayrollEntry/PayrollRunEntry entries."""
        from payroll.models import PayrollRun, PayrollEntry, PayrollRunEntry, EmployeeProfile

        requested_closed = bool(self.cleaned_data.get("closed", False))
        company = get_user_company(self.user)

        # Create the PayrollRun instance
        payt = PayrollRun.objects.create(
            name=self.cleaned_data["name"],
            paydays=self.cleaned_data["paydays"],
            is_active=self.cleaned_data.get("is_active", False),
            closed=False,
            company=company,
        )

        skipped_employees = []
        for emp_id in self._selected_employee_ids:
            employee = EmployeeProfile.objects.get(
                id=emp_id,
                company=company,
                status="active",
            )
            is_blocked, reason = _employee_blocked_for_payday(
                employee, self.cleaned_data["paydays"]
            )
            if is_blocked:
                full_name = f"{employee.first_name} {employee.last_name}".strip()
                skipped_employees.append(f"{full_name or employee.emp_id} ({reason})")
                continue

            payvar = PayrollEntry.objects.create(
                pays=employee,
                company=company,
                status="active",
            )
            PayrollRunEntry.objects.create(payroll_run=payt, payroll_entry=payvar)

        if requested_closed:
            payt.closed = True
            payt.save(update_fields=["closed"])

        payt._skipped_employee_reasons = skipped_employees
        return payt



class PayrollEntryCreateForm(forms.Form):
    """Enhanced form for creating PayrollEntry (Payroll Variables) for multiple employees."""

    employee_ids = forms.CharField(
        widget=forms.HiddenInput(attrs={"name": "employee_ids"}),
        required=False,
    )
    is_housing = forms.BooleanField(
        label="NHF Deductable",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "h-4 w-4 text-primary-600 border-secondary-300 rounded focus:ring-primary-500"
            }
        ),
    )
    is_nhif = forms.BooleanField(
        label="NHIF Deductable",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "h-4 w-4 text-primary-600 border-secondary-300 rounded focus:ring-primary-500"
            }
        ),
    )
    status = forms.ChoiceField(
        label="Status",
        choices=models.PayrollEntry._meta.get_field("status").choices,
        initial="pending",
        widget=forms.Select(
            attrs={
                "class": "w-full px-4 py-2.5 border border-secondary-300 rounded-xl focus:ring-2 focus:ring-primary-500 focus:border-primary-500 text-sm bg-white"
            }
        ),
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

    def save(self):
        """Create PayrollEntry entries for selected employees."""
        from payroll.models import PayrollEntry, EmployeeProfile

        payvars = []

        # Get selected employee IDs
        employee_ids_str = self.cleaned_data.get("employee_ids", "")
        if employee_ids_str:
            employee_ids = [
                int(eid.strip()) for eid in employee_ids_str.split(",") if eid.strip()
            ]

            # Create PayrollEntry entries for selected employees
            for emp_id in employee_ids:
                try:
                    employee = EmployeeProfile.objects.get(
                        id=emp_id,
                        company=get_user_company(self.user),
                    )
                    payvar = PayrollEntry.objects.create(
                        pays=employee,
                        status=self.cleaned_data.get("status", "pending"),
                    )
                    payvars.append(payvar)
                except EmployeeProfile.DoesNotExist:
                    continue

        return payvars


