# Generated by Django 5.1.5 on 2026-05-14 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tenant_scope_accounting'),
        ('company', '0003_backfill_memberships'),
        ('inventory', '0003_purchaseorder_purchasereceipt_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories_as_cogs', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='sales_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories_as_sales_revenue', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_sales_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_wht_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='standard_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='wht_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_wht_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='wht_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_suppliers_as_wht_payable', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='document_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALES_INVOICE', 'Sales Invoice'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('STOCK_COUNT', 'Stock Count')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Opening'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], max_length=20),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('default_wht_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='company.company')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_customers_as_receivable', to='accounting.account')),
                ('wht_receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_customers_as_wht_receivable', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='company.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='inventory.customer')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice', to='inventory.inventorydocument')),
            ],
            options={
                'ordering': ['-document__document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('revenue_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cogs_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('wht_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='inventory.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='inventory.stocklocation')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_line', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_customer_company_name'),
        ),
    ]
