# Generated by Django 5.1.5 on 2026-05-14 15:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tenant_scope_accounting'),
        ('company', '0003_backfill_memberships'),
        ('inventory', '0004_inventorycategory_cogs_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydocument',
            name='document_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALES_INVOICE', 'Sales Invoice'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('TAX_REMITTANCE', 'Tax Remittance'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('STOCK_COUNT', 'Stock Count')], max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments_as_cash', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='company.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.customer')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='inventory.inventorydocument')),
            ],
            options={
                'ordering': ['-document__document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_as_cash', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='company.company')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payment', to='inventory.inventorydocument')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-document__document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vat_output_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_input_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_remittances_as_cash', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_remittances', to='company.company')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_remittance', to='inventory.inventorydocument')),
            ],
            options={
                'ordering': ['-document__document_date', '-created_at'],
            },
        ),
    ]
