# Generated by Django 5.1.5 on 2026-05-28 15:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('inventory', '0006_alter_inventorydocument_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='collections_status',
            field=models.CharField(choices=[('CURRENT', 'Current'), ('WATCH', 'Watch'), ('ON_HOLD', 'On Hold'), ('COLLECTIONS', 'Collections')], default='CURRENT', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_due_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=120),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.salesinvoice'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='POSTED', max_length=20),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inventory_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_inventory_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_inventory_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode_format',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryvaluationlayer',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='inventoryvaluationlayer',
            name='remaining_total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='bad_debt_provisioned_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('VOID', 'Void')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='variance_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='adjustment_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_lines', to='inventory.inventorydocument'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='investigation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='system_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='variance_reason',
            field=models.CharField(choices=[('BREAKAGE', 'Breakage'), ('EXPIRY', 'Expiry'), ('THEFT', 'Theft'), ('COUNT_ERROR', 'Count Error'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='serial_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_due_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='discount_terms',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=120),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='discount_taken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='POSTED', max_length=20),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_units', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('COUNTED', 'Counted'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COUNTED', 'Counted'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='DRAFT', max_length=15),
        ),
        migrations.AddIndex(
            model_name='inventoryvaluationlayer',
            index=models.Index(fields=['company', 'item', 'remaining_quantity'], name='inventory_i_company_f9e5df_idx'),
        ),
    ]
