# Generated by Django 5.1.5 on 2026-05-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('inventory', '0007_customer_collections_status_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(default='NG', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_jurisdictions', to='company.company')),
            ],
            options={
                'ordering': ['country_code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT'), ('WHT', 'Withholding Tax')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='company.company')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='inventory.taxjurisdiction')),
            ],
            options={
                'ordering': ['jurisdiction__code', 'tax_type', '-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxjurisdiction',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_tax_jurisdiction_company_code'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.UniqueConstraint(fields=('company', 'jurisdiction', 'tax_type', 'transaction_type', 'effective_from'), name='uniq_tax_rule_company_jurisdiction_type_date'),
        ),
    ]
