# Generated by Django 5.1.5 on 2026-05-29 14:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


LANDED_COST_TABLE = "inventory_landedcost"
LEGACY_LANDED_COST_TABLE = "inventory_landedcost_legacy_pre_0009"


def _table_exists(connection, table_name):
    return table_name in connection.introspection.table_names()


def _column_names(connection, cursor, table_name):
    return {
        column.name
        for column in connection.introspection.get_table_description(cursor, table_name)
    }


def _legacy_name(name):
    if name.startswith("legacy_"):
        return name
    return f"legacy_{name}"[:63]


def _rename_postgres_dependents(cursor, schema_editor, table_name):
    quote = schema_editor.quote_name

    cursor.execute(
        """
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = %s::regclass
        ORDER BY conname
        """,
        [table_name],
    )
    for (constraint_name,) in cursor.fetchall():
        new_name = _legacy_name(constraint_name)
        if new_name != constraint_name:
            cursor.execute(
                f"ALTER TABLE {quote(table_name)} "
                f"RENAME CONSTRAINT {quote(constraint_name)} TO {quote(new_name)}"
            )

    cursor.execute(
        """
        SELECT c.relname
        FROM pg_class c
        JOIN pg_index i ON i.indexrelid = c.oid
        WHERE i.indrelid = %s::regclass
        ORDER BY c.relname
        """,
        [table_name],
    )
    for (index_name,) in cursor.fetchall():
        new_name = _legacy_name(index_name)
        if new_name != index_name:
            cursor.execute(
                f"ALTER INDEX {quote(index_name)} RENAME TO {quote(new_name)}"
            )


def quarantine_legacy_landed_cost(apps, schema_editor):
    connection = schema_editor.connection
    if not _table_exists(connection, LANDED_COST_TABLE) or _table_exists(
        connection, LEGACY_LANDED_COST_TABLE
    ):
        return

    with connection.cursor() as cursor:
        columns = _column_names(connection, cursor, LANDED_COST_TABLE)
        current_columns = {"description", "cost_type", "total_cost", "status"}
        if current_columns.issubset(columns):
            return

        quote = schema_editor.quote_name
        cursor.execute(
            f"ALTER TABLE {quote(LANDED_COST_TABLE)} "
            f"RENAME TO {quote(LEGACY_LANDED_COST_TABLE)}"
        )
        if connection.vendor == "postgresql":
            _rename_postgres_dependents(cursor, schema_editor, LEGACY_LANDED_COST_TABLE)


def restore_legacy_landed_cost(apps, schema_editor):
    connection = schema_editor.connection
    if _table_exists(connection, LANDED_COST_TABLE) or not _table_exists(
        connection, LEGACY_LANDED_COST_TABLE
    ):
        return

    quote = schema_editor.quote_name
    with connection.cursor() as cursor:
        cursor.execute(
            f"ALTER TABLE {quote(LEGACY_LANDED_COST_TABLE)} "
            f"RENAME TO {quote(LANDED_COST_TABLE)}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('inventory', '0008_taxjurisdiction_taxrule_and_more'),
    ]

    operations = [
        migrations.RunPython(
            quarantine_legacy_landed_cost,
            reverse_code=restore_legacy_landed_cost,
        ),
        migrations.CreateModel(
            name='LandedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('cost_type', models.CharField(choices=[('FREIGHT', 'Freight'), ('DUTY', 'Customs Duty'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=30)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ALLOCATED', 'Allocated'), ('POSTED', 'Posted')], default='DRAFT', max_length=20)),
                ('allocation_method', models.CharField(choices=[('BY_VALUE', 'By Value'), ('BY_WEIGHT', 'By Weight'), ('BY_QUANTITY', 'By Quantity')], default='BY_VALUE', max_length=20)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_costs', to='company.company')),
                ('purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landed_costs', to='inventory.purchasereceipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('landed_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.landedcost')),
                ('receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='inventory.purchasereceiptline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PARTIALLY_SHIPPED', 'Partially Shipped'), ('SHIPPED', 'Shipped'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=22)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='company.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.customer')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('shipped_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='inventory.inventoryitem')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.salesorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=80)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='company.company')),
                ('purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='inventory.purchasereceipt')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='inventory.inventoryitem')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bill_lines', to='inventory.purchasereceiptline')),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.vendorbill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('company', 'reference'), name='uniq_sales_order_company_reference'),
        ),
    ]
