# Generated by Django 5.1.5 on 2026-05-29 19:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('inventory', '0009_add_sales_order_vendor_bill_landed_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydocument',
            name='document_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALES_INVOICE', 'Sales Invoice'), ('CUSTOMER_RETURN', 'Customer Return'), ('SUPPLIER_RETURN', 'Supplier Return'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('TAX_REMITTANCE', 'Tax Remittance'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('STOCK_COUNT', 'Stock Count'), ('SALES_ORDER', 'Sales Order'), ('VENDOR_BILL', 'Vendor Bill'), ('LANDED_COST', 'Landed Cost'), ('SHIPMENT', 'Shipment')], max_length=30),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=80)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_STOCK', 'In Stock'), ('ALLOCATED', 'Allocated'), ('SHIPPED', 'Shipped'), ('RECALLED', 'Recalled'), ('EXPIRED', 'Expired')], default='RECEIVED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='company.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['item__sku', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('RETURNED', 'Returned'), ('DEFECTIVE', 'Defective'), ('SCRAPPED', 'Scrapped')], default='IN_STOCK', max_length=20)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('warranty_provider', models.CharField(blank=True, max_length=160)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='company.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.inventoryitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='inventory.lot')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_serials', to='inventory.customer')),
            ],
            options={
                'ordering': ['item__sku', 'serial'],
            },
        ),
        migrations.CreateModel(
            name='TransferShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('PARTIALLY_RECEIVED', 'Partially Received')], default='DISPATCHED', max_length=22)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_shipments', to='company.company')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.stocklocation')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ['-dispatched_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='inventory.inventoryitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_lines', to='inventory.lot')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.transfershipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='SUBMITTED', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='company.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='inventory.customer')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='inventory.serialnumber')),
            ],
            options={
                'ordering': ['-claim_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('company', 'item', 'lot_number'), name='uniq_lot_company_item_number'),
        ),
        migrations.AddConstraint(
            model_name='serialnumber',
            constraint=models.UniqueConstraint(fields=('company', 'item', 'serial'), name='uniq_serial_company_item_number'),
        ),
    ]
