# Generated by Django 5.1.5 on 2026-05-31 19:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_lot_serial_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='revenue_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='customerreturnline',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='default_sales_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_point',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='standard_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationlayer',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationlayer',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationlayer',
            name='remaining_total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationlayer',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationlayer',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='landedcost',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='landedcostallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='received_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='bad_debt_provisioned_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='revenue_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='shipped_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='variance_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='counted_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='system_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='discount_taken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierreturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierreturnline',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierreturnline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierreturnline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierreturnline',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxremittance',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxremittance',
            name='vat_input_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxremittance',
            name='vat_output_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxremittance',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='transfershipment',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='transfershipmentline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transfershipmentline',
            name='received_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18),
        ),
    ]
