# Generated by Django 4.0.2 on 2022-09-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('housing', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('transport', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('bht', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('pension_employee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('pension_employer', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('pension', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('gross_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('consolidated_relief', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('taxable_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('payee', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('water_rate', models.DecimalField(blank=True, decimal_places=2, default=200.0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payroll', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayTManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VariableCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leave', models.BooleanField(default=False)),
                ('is_overtime', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('leave_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('lateness', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('overtime', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('absent', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('damage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('payr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_payroll', to='payroll.payroll')),
            ],
            options={
                'verbose_name_plural': ('Payrolls',),
            },
        ),
        migrations.CreateModel(
            name='PayT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paydays', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('payroll_payday', models.ManyToManyField(related_name='payroll_payday', through='payroll.Payday', to='payroll.VariableCalc')),
            ],
            options={
                'verbose_name_plural': 'PayTs',
            },
        ),
        migrations.AddField(
            model_name='payday',
            name='paydays_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='payroll.payt'),
        ),
        migrations.AddField(
            model_name='payday',
            name='payroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_paydays', to='payroll.variablecalc'),
        ),
    ]
