# Generated by Django 4.0.2 on 2022-10-08 18:27

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import monthyear.models
import payroll.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default=payroll.generator.emp_id, editable=False, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('nin', models.CharField(default=payroll.generator.nin_no, editable=False, max_length=255, unique=True)),
                ('tin_no', models.CharField(default=payroll.generator.tin_no, editable=False, max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_employment', models.DateField(null=True)),
                ('contract_type', models.CharField(choices=[('P', 'Permanent'), ('T', 'Temporary')], max_length=1, null=True)),
                ('phone', models.CharField(default=1234567890, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{3}\\d{9,11}$')], verbose_name='phone number')),
                ('gender', models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], default='others', max_length=255, verbose_name='gender')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(choices=[('C', 'Casual'), ('JS', 'Junior staff'), ('OP', 'Operator'), ('SU', 'SUpervisor'), ('M', 'Manager'), ('COO', 'C.O.O')], default='casual', max_length=255, verbose_name='designation')),
                ('bank', models.CharField(choices=[('Zenith', 'Zenith BANK'), ('Access', 'Access Bank'), ('GTB', 'GT Bank'), ('Jaiz', 'JAIZ Bank'), ('FCMB', 'FCMB'), ('FBN', 'First Bank'), ('Union', 'Union Bank'), ('UBA', 'UBA')], default='Z', max_length=10, verbose_name='employee BANK')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Bank Account Name')),
                ('bank_account_number', models.CharField(max_length=10, unique=True, verbose_name='Bank Account Number')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Payday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PayTManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VariableCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_leave', models.BooleanField(default=False)),
                ('is_overtime', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('leave_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('lateness', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('overtime', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('absent', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('damage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Payroll Variable',
            },
        ),
        migrations.CreateModel(
            name='PayT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=50, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('paydays', monthyear.models.MonthField(help_text='some help...', null=True, verbose_name='Month Value')),
                ('is_active', models.BooleanField(default=False)),
                ('payroll_payday', models.ManyToManyField(related_name='payroll_payday', through='payroll.Payday', to='payroll.Employee')),
            ],
            options={
                'verbose_name_plural': 'PayTs',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('housing', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('transport', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('bht', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('pension_employee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('pension_employer', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('pension', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('gross_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('consolidated_relief', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('taxable_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('payee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('water_rate', models.DecimalField(blank=True, decimal_places=2, default=200.0, max_digits=12)),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('AD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AD', to='payroll.variablecalc')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='payday',
            name='paydays_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='payroll.payt'),
        ),
        migrations.AddField(
            model_name='payday',
            name='payroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_paydays', to='payroll.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pay', to='payroll.payroll'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
