# Generated by Django 4.0.2 on 2022-09-26 19:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variablecalc',
            options={'verbose_name_plural': 'Payroll Variable'},
        ),
        migrations.AddField(
            model_name='payt',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='payt',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='a', editable=True, populate_from='name'),
            preserve_default=False,
        ),
    ]
