# Generated by Django 4.0.2 on 2022-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_variablecalc_options_payt_name_payt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payt',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
