# Generated by Django 4.0.2 on 2022-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payt',
            name='name',
            field=models.CharField(default='test', max_length=50, unique=True),
        ),
    ]
