# Generated by Django 4.0.2 on 2022-09-30 15:40

from django.db import migrations
import monthyear.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payt_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payday',
            name='date',
        ),
        migrations.AlterField(
            model_name='payt',
            name='paydays',
            field=monthyear.models.MonthField(help_text='some help...', null=True, verbose_name='Month Value'),
        ),
    ]
