# Generated by Django 5.1.5 on 2025-03-10 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_department_employeeprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="iou",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Interest rate (e.g., 5.0 for 5%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="iou",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("SALARY_DEDUCTION", "Salary Deduction"),
                    ("DIRECT_PAYMENT", "Direct Payment"),
                ],
                default="SALARY_DEDUCTION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="iou",
            name="reason",
            field=models.TextField(
                blank=True, help_text="Reason for the IOU request", null=True
            ),
        ),
        migrations.AddField(
            model_name="iou",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PAID", "Paid"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="iou",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="iou",
            name="approved_at",
            field=models.DateField(
                blank=True, help_text="Date the IOU is approved", null=True
            ),
        ),
        migrations.AlterField(
            model_name="iou",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Due date of IOU repayment", null=True
            ),
        ),
        migrations.AlterField(
            model_name="iou",
            name="tenor",
            field=models.IntegerField(
                help_text="Tenor of the IOU (in months)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
