# Generated by Django 4.0.2 on 2022-10-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payroll',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='AD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='net_pay',
        ),
        migrations.AddField(
            model_name='employee',
            name='AD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AD', to='payroll.variablecalc'),
        ),
        migrations.AddField(
            model_name='employee',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
