# Generated by Django 4.0.2 on 2022-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payroll_managers_remove_payroll_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecalc',
            name='leave_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
