# Generated by Django 5.1.5 on 2025-04-15 21:28

import django.db.models.deletion
import payroll.generator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payroll", "0005_iou_interest_rate_iou_payment_method_iou_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="iou",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="emp_id",
            field=models.CharField(
                db_index=True,
                default=payroll.generator.emp_id,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="slug",
            field=models.CharField(
                db_index=True,
                max_length=50,
                unique=True,
                verbose_name="Employee slug to identify and route the employee.",
            ),
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
