# Generated by Django 4.0.2 on 2022-10-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_variablecalc_leave_allowance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='AD',
        ),
        migrations.AddField(
            model_name='employee',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='payroll.variablecalc'),
        ),
    ]
