# Generated by Django 5.1.5 on 2025-04-25 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_department_deleted_at_employeeprofile_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payt",
            name="paydays_str",
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in a valid format.",
                        regex="^(?:\\+\\d{1,3}\\s?)?(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4})$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="payroll.employeeprofile",
            ),
        ),
    ]
