# Generated by Django 5.1.5 on 2025-04-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0007_remove_payt_paydays_str_alter_employeeprofile_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="pension_rsa",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
