# Generated by Django 4.0.2 on 2022-10-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_remove_employee_ad_employee_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Bank Account Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('P', 'Permanent'), ('T', 'Temporary')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
