# Generated by Django 5.1.5 on 2025-06-01 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_alter_employeeprofile_pension_rsa"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores a dictionary of changes (old_value, new_value)",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Emergency Contact Name",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in a valid format.",
                        regex="^(?:\\+\\d{1,3}\\s?)?(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4})$",
                    )
                ],
                verbose_name="Emergency Contact Phone Number",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Emergency Contact Relationship",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="next_of_kin_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Next of Kin Name"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="next_of_kin_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in a valid format.",
                        regex="^(?:\\+\\d{1,3}\\s?)?(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4})$",
                    )
                ],
                verbose_name="Next of Kin Phone Number",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="next_of_kin_relationship",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Next of Kin Relationship",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="bank_account_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bank Account Name"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_requests_by_type",
                to="payroll.leavepolicy",
            ),
        ),
    ]
