# Generated by Django 4.0.2 on 2022-10-09 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payroll.generator


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_employment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_pay',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tin_no',
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('nin', models.CharField(default=payroll.generator.nin_no, editable=False, max_length=255, unique=True)),
                ('tin_no', models.CharField(default=payroll.generator.tin_no, editable=False, max_length=255, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('P', 'Permanent'), ('T', 'Temporary')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, default=1234567890, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{3}\\d{9,11}$')], verbose_name='phone number')),
                ('gender', models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], default='others', max_length=255, verbose_name='gender')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(choices=[('C', 'Casual'), ('JS', 'Junior staff'), ('OP', 'Operator'), ('SU', 'SUpervisor'), ('M', 'Manager'), ('COO', 'C.O.O')], default='casual', max_length=255, verbose_name='designation')),
                ('bank', models.CharField(choices=[('Zenith', 'Zenith BANK'), ('Access', 'Access Bank'), ('GTB', 'GT Bank'), ('Jaiz', 'JAIZ Bank'), ('FCMB', 'FCMB'), ('FBN', 'First Bank'), ('Union', 'Union Bank'), ('UBA', 'UBA')], default='Z', max_length=10, verbose_name='employee BANK')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Bank Account Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Bank Account Number')),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='payroll.variablecalc')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='payroll.employee')),
                ('employee_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_pay', to='payroll.payroll')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
