# Generated by Django 5.1.5 on 2025-06-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0009_audittrail_changes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CASUAL", "Casual Leave"),
                    ("SICK", "Sick Leave"),
                    ("ANNUAL", "Annual Leave"),
                    ("MATERNITY", "Maternity Leave"),
                    ("PATERNITY", "Paternity Leave"),
                ],
                default="ANNUAL",
                max_length=20,
            ),
        ),
    ]
