# Generated by Django 4.0.2 on 2022-10-19 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_remove_employee_ad_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(default='def', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(default='we', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, default=1234567890, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{3}\\d{9,11}$')], verbose_name='phone number'),
        ),
    ]
