# Generated by Django 5.1.5 on 2025-07-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_alter_leaverequest_leave_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowance",
            options={"verbose_name_plural": "Allowances"},
        ),
        migrations.RemoveField(
            model_name="allowance",
            name="name",
        ),
        migrations.RemoveField(
            model_name="allowance",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="deduction",
            name="name",
        ),
        migrations.RemoveField(
            model_name="deduction",
            name="percentage",
        ),
        migrations.AddField(
            model_name="allowance",
            name="allowance_type",
            field=models.CharField(
                choices=[
                    ("NULL", "NULL"),
                    ("LV", "Leave Allowance"),
                    ("13th", "13th Month"),
                    ("Ovr", "Overtime"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="Type of allowance",
            ),
        ),
        migrations.AddField(
            model_name="allowance",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allowance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allowances",
                to="payroll.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="deduction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Amount of deduction",
            ),
        ),
        migrations.AddField(
            model_name="deduction",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deduction",
            name="deduction_type",
            field=models.CharField(
                choices=[
                    ("NULL", "NULL"),
                    ("LT", "Lateness"),
                    ("AB", "Absensce"),
                    ("DM", "Damages"),
                    ("MISC", "Miscellenous"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="Type of deduction",
            ),
        ),
        migrations.AddField(
            model_name="deduction",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deductions",
                to="payroll.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="deduction",
            name="reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reason for disciplinary deduction"
            ),
        ),
    ]
