# Generated by Django 5.1.5 on 2025-07-10 12:53

from django.db import migrations
from django.utils import timezone

def populate_created_at(apps, schema_editor):
    Allowance = apps.get_model('payroll', 'Allowance')
    Deduction = apps.get_model('payroll', 'Deduction')

    for obj in Allowance.objects.filter(created_at__isnull=True):
        obj.created_at = timezone.now()
        obj.save(update_fields=['created_at'])

    for obj in Deduction.objects.filter(created_at__isnull=True):
        obj.created_at = timezone.now()
        obj.save(update_fields=['created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_alter_allowance_options_remove_allowance_name_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_created_at, migrations.RunPython.noop),
    ]
