# Generated by Django 4.0.2 on 2022-10-19 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_employeeprofile_email_employeeprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='net_pay',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, default=1234567890, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{3}\\d{9}$')], verbose_name='phone number'),
        ),
    ]
