# Generated by Django 5.1.5 on 2025-07-10 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0012_populate_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payvar",
            name="allowance_id",
        ),
        migrations.RemoveField(
            model_name="payvar",
            name="deduction_id",
        ),
        migrations.AlterField(
            model_name="allowance",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="deduction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
