# Generated by Django 4.0.2 on 2022-10-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_employeeprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='ad',
        ),
        migrations.AddField(
            model_name='variablecalc',
            name='payr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variable_payroll', to='payroll.employeeprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, default=1234567890, max_length=15, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='payday',
            name='payroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_paydays', to='payroll.variablecalc'),
        ),
        migrations.AlterField(
            model_name='payt',
            name='payroll_payday',
            field=models.ManyToManyField(related_name='payroll_payday', through='payroll.Payday', to='payroll.VariableCalc'),
        ),
    ]
