# Generated by Django 5.1.5 on 2025-07-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_remove_payvar_allowance_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="deduction_type",
            field=models.CharField(
                choices=[
                    ("NULL", "NULL"),
                    ("IOU", "IOU Repayment"),
                    ("LT", "Lateness"),
                    ("AB", "Absensce"),
                    ("DM", "Damages"),
                    ("MISC", "Miscellenous"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="Type of deduction",
            ),
        ),
        migrations.CreateModel(
            name="IOUDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iou_deductions",
                        to="payroll.employeeprofile",
                    ),
                ),
                (
                    "iou",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="payroll.iou",
                    ),
                ),
                (
                    "payday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iou_deductions",
                        to="payroll.payt",
                    ),
                ),
            ],
            options={
                "unique_together": {("iou", "payday")},
            },
        ),
    ]
