# Generated by Django 5.1.5 on 2025-07-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0014_alter_deduction_deduction_type_ioudeduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduction",
            name="iou",
            field=models.ForeignKey(
                blank=True,
                help_text="The IOU this deduction is repaying, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repayment_installments",
                to="payroll.iou",
            ),
        ),
    ]
