# Generated by Django 4.0.2 on 2022-10-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_remove_employeeprofile_ad_variablecalc_payr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
