# Generated by Django 5.1.5 on 2025-09-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0016_metric_appraisal_review_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appraisal",
            name="employees",
        ),
        migrations.CreateModel(
            name="AppraisalAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appraisal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.appraisal",
                    ),
                ),
                (
                    "appraisee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisee_assignments",
                        to="payroll.employeeprofile",
                    ),
                ),
                (
                    "appraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraiser_assignments",
                        to="payroll.employeeprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("appraisal", "appraisee", "appraiser")},
            },
        ),
    ]
