# Generated by Django 4.0.2 on 2022-10-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_remove_variablecalc_basic_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netpay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='payroll.employeeprofile')),
                ('var', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var', to='payroll.variablecalc')),
            ],
        ),
    ]
