# Generated by Django 5.1.5 on 2025-09-28 22:13

from django.db import migrations

METRICS = [
    ("Job Knowledge & Skills", "Understands job responsibilities and demonstrates technical competence. Stays updated with new methods and industry standards."),
    ("Work Quality", "Accuracy, thoroughness, and attention to detail. Meets performance standards consistently."),
    ("Productivity & Efficiency", "Completes tasks on time. Manages workload effectively and prioritizes well."),
    ("Communication", "Effectively communicates with team members and clients. Listens actively and responds constructively."),
    ("Teamwork & Collaboration", "Cooperates with colleagues and contributes to team success. Respects diverse perspectives and fosters collaboration."),
    ("Initiative & Problem-Solving", "Takes proactive steps to improve processes. Suggests creative solutions to challenges."),
    ("Attendance & Punctuality", "Maintains regular attendance. Arrives on time and adheres to schedules."),
    ("Overall Performance", "General Comments"),
]

def seed_metrics(apps, schema_editor):
    Metric = apps.get_model('payroll', 'Metric')
    for name, description in METRICS:
        Metric.objects.create(name=name, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_remove_appraisal_employees_appraisalassignment'),
    ]

    operations = [
        migrations.RunPython(seed_metrics),
    ]
