# Generated by Django 5.1.5 on 2025-09-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0018_auto_20250928_2313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="comments",
        ),
        migrations.AddField(
            model_name="rating",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="self_assessment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
