# Generated by Django 5.1.5 on 2025-09-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0019_remove_review_comments_rating_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="pension_rsa",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
