# Generated by Django 5.1.5 on 2025-09-29 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0020_alter_employeeprofile_pension_rsa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in a valid format.",
                        regex="^(?:\\+\\d{1,3}\\s?)?(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4})$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
