# Generated by Django 5.1.5 on 2025-09-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0021_alter_employeeprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="slug",
            field=models.CharField(
                db_index=True,
                max_length=50,
                verbose_name="Employee slug to identify and route the employee.",
            ),
        ),
    ]
