# Generated by Django 5.1.5 on 2025-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0022_alter_employeeprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="available_days",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="payt",
            name="slug",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
