# Generated by Django 5.1.5 on 2025-12-22 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0023_leaverequest_available_days_alter_payt_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="available_days",
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="hr_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="is_half_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="override_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CASUAL", "Casual Leave"),
                    ("SICK", "Sick Leave"),
                    ("ANNUAL", "Annual Leave"),
                    ("MATERNITY", "Maternity Leave"),
                    ("PATERNITY", "Paternity Leave"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaveAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="payroll.leaverequest",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("annual_leave", models.PositiveIntegerField(default=10)),
                ("sick_leave", models.PositiveIntegerField(default=5)),
                ("casual_leave", models.PositiveIntegerField(default=3)),
                ("maternity_leave", models.PositiveIntegerField(default=40)),
                ("paternity_leave", models.PositiveIntegerField(default=14)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balance",
                        to="payroll.employeeprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "year")},
            },
        ),
    ]
