# Generated by Django 5.1.5 on 2025-12-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0026_remove_employee_id_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("LEAVE_APPROVED", "Leave Approved"),
                            ("LEAVE_REJECTED", "Leave Rejected"),
                            ("LEAVE_PENDING", "Leave Pending"),
                            ("IOU_APPROVED", "IOU Approved"),
                            ("IOU_REJECTED", "IOU Rejected"),
                            ("IOU_PENDING", "IOU Pending"),
                            ("PAYSLIP_AVAILABLE", "Payslip Available"),
                            ("PAYROLL_PROCESSED", "Payroll Processed"),
                            ("APPRAISAL_ASSIGNED", "Appraisal Assigned"),
                            ("APPRAISAL_COMPLETED", "Appraisal Completed"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                            ("INFO", "Information"),
                        ],
                        default="INFO",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appraisal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="payroll.appraisal",
                    ),
                ),
                (
                    "iou",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="payroll.iou",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="payroll.leaverequest",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="payroll.payt",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="payroll.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="payroll_not_recipie_79f6ef_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="payroll_not_created_a6317f_idx"
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="payroll_not_notific_7d6362_idx",
                    ),
                ],
            },
        ),
    ]
