# Generated by Django 5.1.5 on 2025-12-28 14:13

import uuid
from django.db import migrations, models


def convert_notification_id_to_uuid(apps, schema_editor):
    """
    Convert Notification.id from bigint to UUID.
    This is done in a separate function to handle the data migration properly.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    # Add a temporary UUID column
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            ADD COLUMN new_id uuid DEFAULT gen_random_uuid() NOT NULL
        """
        )

        # Drop the old primary key constraint
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            DROP CONSTRAINT payroll_notification_pkey
        """
        )

        # Drop the old id column
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            DROP COLUMN id
        """
        )

        # Rename new_id to id
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            RENAME COLUMN new_id TO id
        """
        )

        # Add primary key constraint
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            ADD CONSTRAINT payroll_notification_pkey PRIMARY KEY (id)
        """
        )


def reverse_convert_notification_id_to_uuid(apps, schema_editor):
    """
    Reverse the UUID conversion (for rollback).
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Add a temporary bigint column
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            ADD COLUMN new_id bigserial NOT NULL
        """
        )

        # Drop the old primary key constraint
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            DROP CONSTRAINT payroll_notification_pkey
        """
        )

        # Drop the old id column
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            DROP COLUMN id
        """
        )

        # Rename new_id to id
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            RENAME COLUMN new_id TO id
        """
        )

        # Add primary key constraint
        cursor.execute(
            """
            ALTER TABLE payroll_notification 
            ADD CONSTRAINT payroll_notification_pkey PRIMARY KEY (id)
        """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0027_notification"),
    ]

    operations = [
        # Convert the existing Notification.id from bigint to UUID
        migrations.RunPython(
            convert_notification_id_to_uuid,
            reverse_convert_notification_id_to_uuid,
        ),
        # Update Django's internal state to reflect the UUID change
        # This is a no-op in SQL but updates Django's model state
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
