# Generated by Django 5.1.5 on 2025-12-28 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payroll", "0028_convert_notification_id_to_uuid"),
    ]

    operations = [
        # Create new models with UUID primary keys
        migrations.CreateModel(
            name="ArchivedNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_notification_id", models.UUIDField()),
                ("notification_type", models.CharField(max_length=50)),
                ("priority", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_status", models.JSONField(blank=True, default=dict)),
                ("is_aggregated", models.BooleanField(default=False)),
                ("aggregation_key", models.CharField(blank=True, max_length=255)),
                ("aggregation_count", models.IntegerField(default=0)),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "action_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("template_context", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("leave_request_id", models.UUIDField(blank=True, null=True)),
                ("iou_id", models.UUIDField(blank=True, null=True)),
                ("payroll_id", models.UUIDField(blank=True, null=True)),
                ("appraisal_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Archived Notification",
                "verbose_name_plural": "Archived Notifications",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("sms", "SMS"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("platform", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "sms_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sms_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Notification Delivery Log",
                "verbose_name_plural": "Notification Delivery Logs",
                "ordering": ["-queued_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=False)),
                (
                    "in_app_priority_threshold",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical Only"),
                            ("HIGH", "High and Above"),
                            ("MEDIUM", "Medium and Above"),
                            ("LOW", "All Notifications"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "email_priority_threshold",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical Only"),
                            ("HIGH", "High and Above"),
                            ("MEDIUM", "Medium and Above"),
                            ("LOW", "All Notifications"),
                        ],
                        default="HIGH",
                        max_length=20,
                    ),
                ),
                (
                    "push_priority_threshold",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical Only"),
                            ("HIGH", "High and Above"),
                            ("MEDIUM", "Medium and Above"),
                            ("LOW", "All Notifications"),
                        ],
                        default="HIGH",
                        max_length=20,
                    ),
                ),
                (
                    "sms_priority_threshold",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical Only"),
                            ("HIGH", "High and Above"),
                            ("MEDIUM", "Medium and Above"),
                            ("LOW", "All Notifications"),
                        ],
                        default="CRITICAL",
                        max_length=20,
                    ),
                ),
                (
                    "email_digest_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "push_digest_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "quiet_hours_timezone",
                    models.CharField(default="UTC", max_length=50),
                ),
                (
                    "max_notifications_per_hour",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum notifications per hour per channel",
                    ),
                ),
                ("type_preferences", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("sms", "SMS"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "subject_template",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("body_template", models.TextField()),
                ("required_variables", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["code", "language", "-version"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTypePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("LEAVE_APPROVED", "Leave Approved"),
                            ("LEAVE_REJECTED", "Leave Rejected"),
                            ("LEAVE_PENDING", "Leave Pending"),
                            ("LEAVE_CANCELLED", "Leave Cancelled"),
                            ("LEAVE_REMINDER", "Leave Reminder"),
                            ("IOU_APPROVED", "IOU Approved"),
                            ("IOU_REJECTED", "IOU Rejected"),
                            ("IOU_PENDING", "IOU Pending"),
                            ("IOU_DUE", "IOU Payment Due"),
                            ("PAYSLIP_AVAILABLE", "Payslip Available"),
                            ("PAYROLL_PROCESSED", "Payroll Processed"),
                            ("PAYROLL_FAILED", "Payroll Processing Failed"),
                            ("SALARY_DISBURSED", "Salary Disbursed"),
                            ("APPRAISAL_ASSIGNED", "Appraisal Assigned"),
                            ("APPRAISAL_COMPLETED", "Appraisal Completed"),
                            ("APPRAISAL_REMINDER", "Appraisal Reminder"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=False)),
                (
                    "min_priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("custom_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Type Preference",
                "verbose_name_plural": "Notification Type Preferences",
                "ordering": ["employee", "notification_type"],
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="action_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="aggregated_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="aggregated_notifications",
                to="payroll.notification",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="aggregation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="aggregation_key",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery_status",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_aggregated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critical"),
                    ("HIGH", "High"),
                    ("MEDIUM", "Medium"),
                    ("LOW", "Low"),
                ],
                db_index=True,
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="template_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("LEAVE_APPROVED", "Leave Approved"),
                    ("LEAVE_REJECTED", "Leave Rejected"),
                    ("LEAVE_PENDING", "Leave Pending"),
                    ("LEAVE_CANCELLED", "Leave Cancelled"),
                    ("LEAVE_REMINDER", "Leave Reminder"),
                    ("IOU_APPROVED", "IOU Approved"),
                    ("IOU_REJECTED", "IOU Rejected"),
                    ("IOU_PENDING", "IOU Pending"),
                    ("IOU_DUE", "IOU Payment Due"),
                    ("PAYSLIP_AVAILABLE", "Payslip Available"),
                    ("PAYROLL_PROCESSED", "Payroll Processed"),
                    ("PAYROLL_FAILED", "Payroll Processing Failed"),
                    ("SALARY_DISBURSED", "Salary Disbursed"),
                    ("APPRAISAL_ASSIGNED", "Appraisal Assigned"),
                    ("APPRAISAL_COMPLETED", "Appraisal Completed"),
                    ("APPRAISAL_REMINDER", "Appraisal Reminder"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("INFO", "Information"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority"], name="payroll_not_priorit_6b9994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "priority"], name="payroll_not_recipie_da54db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_archived"],
                name="payroll_not_recipie_b09424_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["aggregation_key"], name="payroll_not_aggrega_f5d720_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_deleted"], name="payroll_not_is_dele_2df54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["expires_at"], name="payroll_not_expires_5f4f57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at", "is_read"],
                name="payroll_not_recipie_f20805_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "priority", "-created_at"],
                name="payroll_not_recipie_233269_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_deleted", "-created_at"],
                name="payroll_not_recipie_406f2a_idx",
            ),
        ),
        migrations.AddField(
            model_name="archivednotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archived_notifications",
                to="payroll.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliverylog",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_logs",
                to="payroll.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliverylog",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_logs",
                to="payroll.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to="payroll.employeeprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["code", "language"], name="payroll_not_code_dd3bf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["channel", "is_active"], name="payroll_not_channel_365926_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationtemplate",
            unique_together={("code", "channel", "language", "version")},
        ),
        migrations.AddField(
            model_name="notificationtypepreference",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_preferences",
                to="payroll.employeeprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="archivednotification",
            index=models.Index(
                fields=["recipient", "archived_at"],
                name="payroll_arc_recipie_43718b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="archivednotification",
            index=models.Index(
                fields=["archived_at"], name="payroll_arc_archive_66dd7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archivednotification",
            index=models.Index(
                fields=["notification_type"], name="payroll_arc_notific_ab5d41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archivednotification",
            index=models.Index(
                fields=["original_notification_id"],
                name="payroll_arc_origina_8707c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["notification", "channel"],
                name="payroll_not_notific_7114b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["status", "queued_at"], name="payroll_not_status_f66944_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["recipient", "queued_at"], name="payroll_not_recipie_bd5314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["channel", "status"], name="payroll_not_channel_7f6bc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["retry_count"], name="payroll_not_retry_c_26ed1b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationtypepreference",
            unique_together={("employee", "notification_type")},
        ),
    ]
