# Generated by Django 5.1.5 on 2026-02-03 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0029_archivednotification_notificationdeliverylog_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payroll",
            old_name="consolidated_relief",
            new_name="rent_relief",
        ),
        migrations.AddField(
            model_name="payroll",
            name="rent_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                help_text=" Annual rent paid by employee. This is used to calculate the employee's rent relief. ",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="gross_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                help_text=" Annual gross income of employee. ",
                max_digits=12,
            ),
        ),
    ]
