# Generated by Django 5.1.5 on 2026-02-03 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0030_rename_consolidated_relief_payroll_rent_relief_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="rent_paid",
        ),
        migrations.RemoveField(
            model_name="payvar",
            name="employee_health",
        ),
        migrations.RemoveField(
            model_name="payvar",
            name="emplyr_health",
        ),
        migrations.RemoveField(
            model_name="payvar",
            name="is_housing",
        ),
        migrations.RemoveField(
            model_name="payvar",
            name="is_nhif",
        ),
        migrations.RemoveField(
            model_name="payvar",
            name="nhf",
        ),
        migrations.RemoveField(
            model_name="payvar",
            name="nhif",
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="rent_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                help_text=" Annual rent paid by employee. This is used to calculate the employee's rent relief. ",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="employee_health",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="emplyr_health",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="is_housing",
            field=models.BooleanField(default=False, verbose_name="is NHF deductable"),
        ),
        migrations.AddField(
            model_name="payroll",
            name="is_nhif",
            field=models.BooleanField(default=False, verbose_name="is NHIF deductable"),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nhf",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nhif",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
    ]
