# Generated by Django 5.1.5 on 2026-02-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0033_rename_payrollrunentry_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollrun",
            options={"verbose_name_plural": "Payroll Runs"},
        ),
        migrations.AlterField(
            model_name="payrollrunentry",
            name="payroll_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_run_entries",
                to="payroll.payrollentry",
            ),
        ),
        migrations.AlterField(
            model_name="payrollrunentry",
            name="payroll_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_run_entries",
                to="payroll.payrollrun",
            ),
        ),
    ]
