# Generated by Django 5.1.5 on 2026-02-17 07:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('payroll', '0037_remove_payroll_rent_relief'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('housing_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('transport_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('pension_employee_percentage', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('pension_employer_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('nhf_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_setting', to='company.company')),
            ],
            options={
                'verbose_name': 'Company Payroll Setting',
                'verbose_name_plural': 'Company Payroll Settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyHealthInsuranceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for no upper limit.', max_digits=12, null=True)),
                ('employee_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('employer_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insurance_tiers', to='payroll.companypayrollsetting')),
            ],
            options={
                'verbose_name': 'Health Insurance Tier',
                'verbose_name_plural': 'Health Insurance Tiers',
                'ordering': ('sort_order', 'min_salary'),
            },
        ),
    ]
