# Generated by Django 5.1.5 on 2026-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_companypayrollsetting_thirteenth_month_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='hmo_provider',
            field=models.CharField(blank=True, choices=[('AXA', 'AXA Mansard Health'), ('AVON', 'Avon HMO'), ('CLEARLINE', 'Clearline HMO'), ('HYGEIA', 'Hygeia HMO'), ('INTEGRATED', 'Integrated Healthcare Limited'), ('RELIANCE', 'Reliance HMO'), ('TOTALHEALTH', 'Total Health Trust'), ('WELLNESS', 'Wellness Healthcare')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pension_fund_manager',
            field=models.CharField(blank=True, choices=[('AIICO', 'AIICO Pension Managers'), ('APT', 'APT Pension Funds Managers'), ('ARM', 'ARM Pension Managers'), ('FCMB', 'FCMB Pensions'), ('FIDELITY', 'Fidelity Pension Managers'), ('IEI', 'IEI-Anchor Pensions'), ('OAK', 'OAK Pensions'), ('PAL', 'PAL Pensions'), ('PENCOM', 'Pension Alliance Limited'), ('SIGMA', 'Sigma Pensions'), ('STANBIC', 'Stanbic IBTC Pension Managers'), ('TRUSTFUND', 'Trustfund Pensions'), ('VERITAS', 'Veritas Glanvills Pensions')], max_length=30, null=True),
        ),
    ]
