# Generated by Django 5.1.5 on 2026-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_employeeprofile_hmo_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('pending', 'PENDING'), ('suspended', 'SUSPENDED'), ('terminated', 'TERMINATED')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('pending', 'PENDING'), ('suspended', 'SUSPENDED'), ('terminated', 'TERMINATED')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('pending', 'PENDING'), ('suspended', 'SUSPENDED'), ('terminated', 'TERMINATED')], default='pending', max_length=10),
        ),
    ]
