# Generated by Django 5.1.5 on 2026-02-23 18:23

import django.db.models.deletion
from django.db import migrations, models


def populate_appraisal_company(apps, schema_editor):
    Appraisal = apps.get_model("payroll", "Appraisal")
    AppraisalAssignment = apps.get_model("payroll", "AppraisalAssignment")
    Review = apps.get_model("payroll", "Review")

    for appraisal in Appraisal.objects.filter(company__isnull=True):
        assignment = (
            AppraisalAssignment.objects.filter(appraisal=appraisal)
            .select_related("appraisee__company")
            .first()
        )
        if assignment and assignment.appraisee and assignment.appraisee.company_id:
            appraisal.company_id = assignment.appraisee.company_id
            appraisal.save(update_fields=["company"])
            continue

        review = (
            Review.objects.filter(appraisal=appraisal)
            .select_related("employee__company")
            .first()
        )
        if review and review.employee and review.employee.company_id:
            appraisal.company_id = review.employee.company_id
            appraisal.save(update_fields=["company"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('payroll', '0042_alter_employeeprofile_status_alter_payroll_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ('-start_date', '-id')},
        ),
        migrations.AddField(
            model_name='appraisal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='company.company'),
        ),
        migrations.RunPython(populate_appraisal_company, noop_reverse),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('review', 'metric'), name='unique_metric_rating_per_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('appraisal', 'employee', 'reviewer'), name='unique_review_per_assignment'),
        ),
    ]
