# Generated by Django 5.1.5 on 2026-02-26 09:40

import payroll.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_alter_appraisal_options_appraisal_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='tin_no',
            field=models.CharField(default=payroll.generator.tin_no, max_length=255, unique=True),
        ),
    ]
