# Generated by Django 5.1.5 on 2026-02-26 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_alter_employeeprofile_tin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +2348012345678 or 08012345678).', regex='^(?:\\+?[1-9]\\d{7,14}|0\\d{10})$')], verbose_name='Emergency Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +2348012345678 or 08012345678).', regex='^(?:\\+?[1-9]\\d{7,14}|0\\d{10})$')], verbose_name='Next of Kin Phone Number'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +2348012345678 or 08012345678).', regex='^(?:\\+?[1-9]\\d{7,14}|0\\d{10})$')], verbose_name='phone number'),
        ),
    ]
