# Generated by Django 5.1.5 on 2026-02-26 16:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0045_alter_employeeprofile_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iou',
            name='repayment_deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Percentage of monthly salary to deduct for IOU repayment.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
