# Generated by Django 5.1.5 on 2026-05-21 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('payroll', '0051_leave_allowance_email_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('stage_type', models.CharField(choices=[('sourced', 'Sourced'), ('screening', 'Screening'), ('structured_interview', 'Structured Interview'), ('scorecard_review', 'Scorecard Review'), ('reference_check', 'Reference Check'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=40)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('requires_scorecard', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('guidance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_stages', to='company.company')),
            ],
            options={
                'ordering': ['sequence', 'name'],
                'unique_together': {('company', 'stage_type')},
            },
        ),
        migrations.CreateModel(
            name='HiringCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_process', 'In process'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='new', max_length=20)),
                ('consent_to_process', models.BooleanField(default=False)),
                ('structured_notes', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_candidates', to='company.company')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_candidates', to='payroll.hiringstage')),
            ],
            options={
                'ordering': ['-applied_at', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='sent', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='payroll.hiringcandidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On hold'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('compensation_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('compensation_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('outcomes_90_days', models.TextField(blank=True)),
                ('must_have_criteria', models.JSONField(blank=True, default=list)),
                ('scorecard_template', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requisitions', to='company.company')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_job_requisitions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_job_requisitions', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='payroll.position')),
            ],
            options={
                'ordering': ['-opened_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='hiringcandidate',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='payroll.jobrequisition'),
        ),
        migrations.CreateModel(
            name='HiringStageScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('competency_scores', models.JSONField(blank=True, default=dict)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('recommendation', models.CharField(choices=[('strong_yes', 'Strong yes'), ('yes', 'Yes'), ('no', 'No'), ('strong_no', 'Strong no')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='payroll.hiringcandidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_scorecards', to='company.company')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_scorecards', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scorecards', to='payroll.hiringstage')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('candidate', 'stage', 'interviewer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='hiringcandidate',
            unique_together={('requisition', 'email')},
        ),
    ]
