# Generated by Django 5.1.3 on 2026-05-28 14:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import payroll.fields
import payroll.generator
from django.conf import settings
from django.db import migrations, models


SENSITIVE_EMPLOYEE_FIELDS = (
    "nin",
    "tin_no",
    "bank_account_name",
    "bank_account_number",
    "pension_rsa",
    "emergency_contact_phone",
    "next_of_kin_phone",
)


def encrypt_existing_employee_sensitive_fields(apps, schema_editor):
    EmployeeProfile = apps.get_model("payroll", "EmployeeProfile")
    for employee in EmployeeProfile.objects.all().iterator():
        changed_fields = [
            field
            for field in SENSITIVE_EMPLOYEE_FIELDS
            if getattr(employee, field, None)
        ]
        if changed_fields:
            employee.save(update_fields=changed_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('payroll', '0052_hiringstage_hiringcandidate_joboffer_jobrequisition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_probation_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('on_probation', 'On probation'), ('confirmed', 'Confirmed'), ('extended', 'Extended')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='hiringcandidate',
            name='consent_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringcandidate',
            name='consent_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringcandidate',
            name='consent_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_over_annual_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carryover_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='carryover_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='carryover_expires_after_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='statutory_min_days',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='bank_account_name',
            field=payroll.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Name'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='bank_account_number',
            field=payroll.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='emergency_contact_phone',
            field=payroll.fields.EncryptedCharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +2348012345678 or 08012345678).', regex='^(?:\\+?[1-9]\\d{7,14}|0\\d{10})$')], verbose_name='Emergency Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='next_of_kin_phone',
            field=payroll.fields.EncryptedCharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +2348012345678 or 08012345678).', regex='^(?:\\+?[1-9]\\d{7,14}|0\\d{10})$')], verbose_name='Next of Kin Phone Number'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='nin',
            field=payroll.fields.EncryptedCharField(default=payroll.generator.nin_no, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='pension_rsa',
            field=payroll.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='tin_no',
            field=payroll.fields.EncryptedCharField(default=payroll.generator.tin_no, max_length=255, unique=True),
        ),
        migrations.RunPython(encrypt_existing_employee_sensitive_fields, noop_reverse),
        migrations.CreateModel(
            name='LeaveBlackoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_blackout_periods', to='company.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_blackout_periods', to='payroll.department')),
            ],
            options={
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR')], max_length=20)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.leaverequest')),
            ],
            options={
                'ordering': ['approved_at'],
                'unique_together': {('leave_request', 'step')},
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_changes', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='payroll.employeeprofile')),
                ('salary_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_history', to='payroll.payroll')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'unique_together': {('employee', 'salary_config', 'effective_date')},
            },
        ),
    ]
