# Generated by Django 5.1.3 on 2026-05-28 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_employeeprofile_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='payroll.employeeprofile'),
        ),
    ]
