# Generated by Django 5.1.5 on 2026-05-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0054_alter_leavebalance_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapproval',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='step',
            field=models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR'), ('director', 'Director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_PENDING', 'Leave Pending'), ('LEAVE_CANCELLED', 'Leave Cancelled'), ('LEAVE_REMINDER', 'Leave Reminder'), ('IOU_APPROVED', 'IOU Approved'), ('IOU_REJECTED', 'IOU Rejected'), ('IOU_PENDING', 'IOU Pending'), ('IOU_DUE', 'IOU Payment Due'), ('LEAVE_ESCALATED', 'Leave Request Escalated'), ('IOU_ESCALATED', 'IOU Request Escalated'), ('APPROVAL_REMINDER', 'Approval Reminder'), ('PAYSLIP_AVAILABLE', 'Payslip Available'), ('PAYROLL_PROCESSED', 'Payroll Processed'), ('PAYROLL_FAILED', 'Payroll Processing Failed'), ('SALARY_DISBURSED', 'Salary Disbursed'), ('APPRAISAL_ASSIGNED', 'Appraisal Assigned'), ('APPRAISAL_COMPLETED', 'Appraisal Completed'), ('APPRAISAL_REMINDER', 'Appraisal Reminder'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtypepreference',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_PENDING', 'Leave Pending'), ('LEAVE_CANCELLED', 'Leave Cancelled'), ('LEAVE_REMINDER', 'Leave Reminder'), ('IOU_APPROVED', 'IOU Approved'), ('IOU_REJECTED', 'IOU Rejected'), ('IOU_PENDING', 'IOU Pending'), ('IOU_DUE', 'IOU Payment Due'), ('LEAVE_ESCALATED', 'Leave Request Escalated'), ('IOU_ESCALATED', 'IOU Request Escalated'), ('APPROVAL_REMINDER', 'Approval Reminder'), ('PAYSLIP_AVAILABLE', 'Payslip Available'), ('PAYROLL_PROCESSED', 'Payroll Processed'), ('PAYROLL_FAILED', 'Payroll Processing Failed'), ('SALARY_DISBURSED', 'Salary Disbursed'), ('APPRAISAL_ASSIGNED', 'Appraisal Assigned'), ('APPRAISAL_COMPLETED', 'Appraisal Completed'), ('APPRAISAL_REMINDER', 'Appraisal Reminder'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=50),
        ),
    ]
