# Generated by Django 5.1.5 on 2026-05-31 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_backfill_memberships'),
        ('payroll', '0055_add_escalation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_retention_days', models.PositiveIntegerField(default=365)),
                ('survey_retention_days', models.PositiveIntegerField(default=730)),
                ('disciplinary_retention_days', models.PositiveIntegerField(default=1095)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_retention_policy', to='company.company')),
            ],
            options={
                'verbose_name': 'HR Retention Policy',
                'verbose_name_plural': 'HR Retention Policies',
            },
        ),
        migrations.CreateModel(
            name='CandidateConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('consent_given', models.BooleanField(default=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='payroll.hiringcandidate')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_candidate_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['candidate', 'consent_given'], name='payroll_can_candida_dd2c55_idx'), models.Index(fields=['expires_at'], name='payroll_can_expires_18854c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveCarryover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.PositiveIntegerField()),
                ('to_year', models.PositiveIntegerField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_carryovers', to='payroll.employeeprofile')),
                ('source_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_carryovers', to='payroll.leavebalance')),
            ],
            options={
                'ordering': ['-to_year', 'employee_id'],
                'unique_together': {('employee', 'from_year', 'to_year')},
            },
        ),
    ]
