# Generated by Codex on 2026-06-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_backfill_memberships"),
        ("payroll", "0056_hrretentionpolicy_candidateconsent_leavecarryover"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveDataAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=64)),
                ("purpose", models.CharField(max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensitive_employee_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_data_accesses",
                        to="company.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_data_accesses",
                        to="payroll.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
                "permissions": [
                    (
                        "view_sensitive_employee_data",
                        "Can view sensitive employee data",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccess",
            index=models.Index(
                fields=["employee", "timestamp"],
                name="payroll_sen_employe_8ae580_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccess",
            index=models.Index(
                fields=["company", "timestamp"],
                name="payroll_sen_company_5e08a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccess",
            index=models.Index(
                fields=["accessed_by", "timestamp"],
                name="payroll_sen_accesse_11a040_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccess",
            index=models.Index(
                fields=["purpose", "timestamp"],
                name="payroll_sen_purpose_9d730d_idx",
            ),
        ),
    ]
