# Generated by Django 5.1.5 on 2026-08-14 13:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0059_leave_allowance_default_annual_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatutoryRateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("effective_date", models.DateField(db_index=True, unique=True)),
                ("paye_bands", models.JSONField(default=list)),
                (
                    "minimum_wage_monthly",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("70000.00"), max_digits=12
                    ),
                ),
                (
                    "pension_employee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "pension_employer_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "nhf_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.50"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statutory Rate Version",
                "verbose_name_plural": "Statutory Rate Versions",
                "ordering": ("effective_date",),
            },
        ),
    ]
