# Generated by Django 5.1.5 on 2026-08-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0061_seed_statutory_rate_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="companypayrollsetting",
            name="health_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "Basic salary (employee 5% / employer 10%)"),
                    (
                        "consolidated",
                        "Consolidated salary (employee 1.75% / employer 3.25%)",
                    ),
                ],
                default="basic",
                help_text="NHIA/NHIS contribution basis used when no health-insurance tier matches the employee's basic salary.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="companypayrollsetting",
            name="hmo_monthly_premium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Negotiated HMO premium per employee per month. When set, the employer pays the premium minus the employee's statutory share.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
