# Generated by Django 5.1.5 on 2026-08-14 14:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0062_companypayrollsetting_health_basis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companypayrollsetting",
            name="itf_applicable",
            field=models.BooleanField(
                default=False,
                help_text="ITF training levy applies to employers with 5+ staff or annual turnover of NGN 50m or more (1% of annual payroll, employer-paid).",
            ),
        ),
        migrations.AddField(
            model_name="companypayrollsetting",
            name="nhia_applicable",
            field=models.BooleanField(
                default=False,
                help_text="NHIA Act 2022 mandates health insurance for employers with 5 or more employees; per-employee enrollment is the is_nhif flag.",
            ),
        ),
        migrations.AddField(
            model_name="companypayrollsetting",
            name="nsitf_applicable",
            field=models.BooleanField(
                default=True,
                help_text="NSITF Employees' Compensation levy (1% of monthly payroll) is employer-paid under the ECA 2010.",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="itf",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nhf_scheme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Not contributing"),
                    ("voluntary", "Voluntary (private sector)"),
                    ("compulsory", "Compulsory (public sector)"),
                ],
                default="none",
                help_text="NHF classification after the 2023 amendment: compulsory for public-sector employees, voluntary for private-sector employees.",
                max_length=20,
            ),
        ),
    ]
