# Generated by Django 5.1.5 on 2026-08-14 14:31

import django.db.models.deletion
import monthyear.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_backfill_memberships"),
        ("payroll", "0063_companypayrollsetting_itf_applicable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemittanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obligation",
                    models.CharField(
                        choices=[
                            ("paye", "PAYE"),
                            ("pension", "Pension"),
                            ("nhf", "NHF"),
                            ("nhia", "NHIA"),
                            ("paye_annual", "PAYE Annual Return"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    monthyear.models.MonthField(
                        help_text="Pay period the remittance relates to (mirrors PayrollRun.paydays).",
                        null=True,
                        verbose_name="Pay period",
                    ),
                ),
                (
                    "remitted_on",
                    models.DateField(
                        blank=True,
                        help_text="Date the remittance/filing was completed; empty means not yet done.",
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Optional remittance reference.",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remittance_records",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remittance Record",
                "verbose_name_plural": "Remittance Records",
                "ordering": ("period", "obligation"),
                "unique_together": {("company", "obligation", "period")},
            },
        ),
    ]
