# Generated by Django 5.1.5 on 2026-08-14 15:14

import hashlib

import payroll.fields
import payroll.generator
from django.conf import settings
from django.db import migrations, models


def _digest(value):
    """Deterministic SHA-256 fingerprint of an identifier plaintext."""
    if not value:
        return None
    return hashlib.sha256(str(value).encode("utf-8")).hexdigest()


def backfill_identifier_digests(apps, schema_editor):
    EmployeeProfile = apps.get_model("payroll", "EmployeeProfile")
    for employee in EmployeeProfile.objects.all().iterator():
        # The historical model decrypts nin/tin_no via EncryptedCharField, so
        # these are plaintext values from the encrypted columns.
        digest_nin = _digest(employee.nin)
        digest_tin = _digest(employee.tin_no)
        if digest_nin != employee.nin_digest or digest_tin != employee.tin_no_digest:
            employee.nin_digest = digest_nin
            employee.tin_no_digest = digest_tin
            employee.save(update_fields=["nin_digest", "tin_no_digest"])


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_backfill_memberships"),
        ("payroll", "0064_remittancerecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={},
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="nin_digest",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="tin_no_digest",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="emp_id",
            field=models.CharField(
                db_index=True,
                default=payroll.generator.emp_id,
                editable=False,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="nin",
            field=payroll.fields.EncryptedCharField(
                default=payroll.generator.nin_no, editable=False, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="tin_no",
            field=payroll.fields.EncryptedCharField(
                default=payroll.generator.tin_no, max_length=255
            ),
        ),
        migrations.RunPython(backfill_identifier_digests, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="employeeprofile",
            constraint=models.UniqueConstraint(
                fields=("company", "emp_id"), name="uniq_employee_company_emp_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeprofile",
            constraint=models.UniqueConstraint(
                fields=("company", "nin_digest"), name="uniq_employee_company_nin"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeprofile",
            constraint=models.UniqueConstraint(
                fields=("company", "tin_no_digest"), name="uniq_employee_company_tin_no"
            ),
        ),
    ]
