# Generated by Django 5.1.5 on 2026-08-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0065_alter_employeeprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remittancerecord",
            name="obligation",
            field=models.CharField(
                choices=[
                    ("paye", "PAYE"),
                    ("pension", "Pension"),
                    ("nhf", "NHF"),
                    ("nhia", "NHIA"),
                    ("paye_annual", "PAYE Annual Return"),
                    ("itf", "ITF"),
                    ("nsitf", "NSITF"),
                ],
                max_length=20,
            ),
        ),
    ]
