# Generated by Django 5.1.5 on 2026-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0066_alter_remittancerecord_obligation"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrun",
            name="payment_date",
            field=models.DateField(
                blank=True,
                help_text="Actual date salaries were paid for this run. When set, statutory deadlines that run from payment (e.g. pension remittance, due within 7 working days) anchor to this date instead of the period start.",
                null=True,
            ),
        ),
    ]
