# Generated by Django 5.1.5 on 2026-08-14 22:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0067_payrollrun_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="companypayrollsetting",
            name="ewa_advance_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Max single advance as % of the employee's earned-but-unpaid net pay in the current pay cycle. Blank uses the 50% rule default.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="companypayrollsetting",
            name="ewa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable self-service earned wage access (EWA) advances.",
            ),
        ),
        migrations.AddField(
            model_name="companypayrollsetting",
            name="ewa_max_per_cycle",
            field=models.PositiveIntegerField(
                blank=True,
                default=2,
                help_text="Max EWA advances an employee may request per pay cycle. Blank uses the rule default of 2.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companypayrollsetting",
            name="ewa_min_days_between",
            field=models.PositiveIntegerField(
                blank=True,
                default=7,
                help_text="Minimum days an employee must wait between EWA advances. Blank uses the rule default of 7.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companypayrollsetting",
            name="ewa_min_take_home_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Take-home guardrail: outstanding advances may not exceed this % of net pay. Blank uses the 50% rule default.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="iou",
            name="is_ewa",
            field=models.BooleanField(
                default=False,
                help_text="True for earned-wage-access advances, which are repaid from the next pay cycle and governed by the company EWA policy.",
            ),
        ),
    ]
