import json
import random
from datetime import datetime

# User data from the provided JSON
users_data = [
    {
        "id": 345,
        "password": "pbkdf2_sha256$870000$1Qg6OUCC3OWjxg9DHtUoV7$k4v2LqE8m+O8p3X+C5QaO7OZto862HU33JiV6Bq0Xxc=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "accountant@payroll.com",
        "first_name": "Accountant",
        "last_name": "User",
        "is_staff": "1",
        "is_active": "1",
        "is_manager": "1",
        "date_joined": "2025-11-29 18:53:02",
    },
    {
        "id": 342,
        "password": "pbkdf2_sha256$870000$XCSTO241HHEukks4CD3IQi$G5QZxwuYZHAt/NdWvCl/oXQN6GJvYEKzgDOHHvewgdM=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "admin@payroll.com",
        "first_name": "Admin",
        "last_name": "User",
        "is_staff": "1",
        "is_active": "1",
        "is_manager": "1",
        "date_joined": "2025-11-29 18:53:01",
    },
    {
        "id": 379,
        "password": "pbkdf2_sha256$870000$whkRdrLmXxJZM4EZ5mMhJx$58fG/YFBH8zN8FCTuyY7r5lOwPVGPcFM5R1ZsvsYT5I=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "andre.kelly567@example.com",
        "first_name": "Andre",
        "last_name": "Kelly",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:09",
    },
    {
        "id": 293,
        "password": "pbkdf2_sha256$870000$YL6Z0FLoKguVplphid8txO$Puu9WE0HSHbRja8VWhTV6hKv/FA2DBKNWVAq4r02q5o=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "angela.harris72@example.com",
        "first_name": "Angela",
        "last_name": "Harris",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:48",
    },
    {
        "id": 298,
        "password": "pbkdf2_sha256$870000$TPjnAC1Mj9XG3awaarUjuC$0Gp0DBDmohirGotrEDV3s9Ji1uVz4AKdgnnLum6CJaY=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "anna.torres777@example.com",
        "first_name": "Anna",
        "last_name": "Torres",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:50",
    },
    {
        "id": 369,
        "password": "pbkdf2_sha256$870000$lvslgFHhLwfRlivDVih5q3$X3hJDdOJ6kFuMOWyc5fTv3DlXdxoYQ76qO8W+3VMK3Q=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "ashley.jenkins270@example.com",
        "first_name": "Ashley",
        "last_name": "Jenkins",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:07",
    },
    {
        "id": 324,
        "password": "pbkdf2_sha256$870000$Gm0xwLDp4QGxLkCOG1vfE2$1kJkzRAYAMjbKLIKdT4neQWhM/dRgLAnNs7t9Jwvvtw=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "ashley.li535@example.com",
        "first_name": "Ashley",
        "last_name": "Li",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:58",
    },
    {
        "id": 315,
        "password": "pbkdf2_sha256$870000$SkLs0mcba0YITnCqyEKWtw$HrxzzuEyin41QfKtdyCZd36z0Sw+7JzCW7N+FJUj5xQ=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "bradley.leach42@example.com",
        "first_name": "Bradley",
        "last_name": "Leach",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:56",
    },
    {
        "id": 320,
        "password": "pbkdf2_sha256$870000$qNk8yz6hhtuhjw0E1U1X8i$0RCxGR5sbit5eDsKbCFIxiObwMrSyay5M9KtoZEwOjk=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "brett.carter599@example.com",
        "first_name": "Brett",
        "last_name": "Carter",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:57",
    },
    {
        "id": 358,
        "password": "pbkdf2_sha256$870000$LNIaDYOfQ2usRMxaPB8V0D$ELPt0m4hP1p/VgzJjZbdvQhRLJ1pGLYCbwQWvmRz5fA=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "bruce.wells936@example.com",
        "first_name": "Bruce",
        "last_name": "Wells",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:05",
    },
    {
        "id": 303,
        "password": "pbkdf2_sha256$870000$2P84c2EakxB9FoHxZWztrj$xUMrOeUXph7Q1SFSXEdSwuVKrd88DelPSJuNWT2rCyM=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "carrie.gutierrez469@example.com",
        "first_name": "Carrie",
        "last_name": "Gutierrez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:52",
    },
    {
        "id": 392,
        "password": "pbkdf2_sha256$870000$2OBz2iBMhRmpmguYXTj2Qa$XzlzBRi/NVMG7r1Nyh50geY+m+2uuybMSf9tFJRo6Eo=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "christine.smith934@example.com",
        "first_name": "Christine",
        "last_name": "Smith",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:12",
    },
    {
        "id": 305,
        "password": "pbkdf2_sha256$870000$vXey9xpOni2RKWOVWmpjnZ$HE2MtoaahmkQwvD2vmYDqMjeT+Bso67EsIsqauvsmlw=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "christopher.armstrong103@example.com",
        "first_name": "Christopher",
        "last_name": "Armstrong",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:53",
    },
    {
        "id": 346,
        "password": "pbkdf2_sha256$870000$bgeqJrDH25rkIYVeeYYNfz$9panU1B1WvwqkyZpTjpx2vrz8jrzo6Rjp7cEDhKXHUs=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "christopher.reed487@example.com",
        "first_name": "Christopher",
        "last_name": "Reed",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "1",
        "date_joined": "2025-11-29 18:53:02",
    },
    {
        "id": 348,
        "password": "pbkdf2_sha256$870000$PePG5t7UZJpRWkj6fSpKiq$U36ktT4IH0WAV/nzMDDHua5Fl0elnp4yOeV8jK3ZiSg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "cindy.freeman647@example.com",
        "first_name": "Cindy",
        "last_name": "Freeman",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:03",
    },
    {
        "id": 387,
        "password": "pbkdf2_sha256$870000$pXXEG8hkOuKzHrSSNSezIt$F1hhsaeE4Jgt1DAPPF7kRPX5+xvUuGeMAa4igmjusqE=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "cindy.quinn394@example.com",
        "first_name": "Cindy",
        "last_name": "Quinn",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:11",
    },
    {
        "id": 314,
        "password": "pbkdf2_sha256$870000$IlzeA0QizzvKa12jxJUBmL$yJm5Fk9DdaspWUI/L1kPzfabnsA31IcOaC/TwXVVHcQ=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "cole.maxwell733@example.com",
        "first_name": "Cole",
        "last_name": "Maxwell",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:56",
    },
    {
        "id": 327,
        "password": "pbkdf2_sha256$870000$w2kyUxqKnl70jBNiJySs7l$6luAMcAebbq4RDTd/q5CzW7ZRgfIh3LyEEhvDfebyog=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "crystal.crane243@example.com",
        "first_name": "Crystal",
        "last_name": "Crane",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:58",
    },
    {
        "id": 377,
        "password": "pbkdf2_sha256$870000$RttLV287fwENyUCJUPiSBi$xb3fQjiYRxWrWS5kK8AMPwTNi86LSlfispVM6t19WAY=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "david.dominguez411@example.com",
        "first_name": "David",
        "last_name": "Dominguez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:09",
    },
    {
        "id": 332,
        "password": "pbkdf2_sha256$870000$WU3JeYVqwWUOOpnx1zSAra$44DgoihkSII0rK29wUm5G4UVAD1OVlI5m8A/FLa6Nd0=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "david.miller568@example.com",
        "first_name": "David",
        "last_name": "Miller",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:59",
    },
    {
        "id": 325,
        "password": "pbkdf2_sha256$870000$TEEqGgm0NdaTXMacDDCJxt$6v+j4mOzVkNYmDmPn+ESnLGYAvt40cKP0sjguBMblFg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "david.ramirez806@example.com",
        "first_name": "David",
        "last_name": "Ramirez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:58",
    },
    {
        "id": 353,
        "password": "pbkdf2_sha256$870000$O7oYd7mRf6Ezr8JDmOSNJr$Nn14D8oGUkfEmCOq4imjdOacGrGJby8n+zRSxuORvI4=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "david.wilkins846@example.com",
        "first_name": "David",
        "last_name": "Wilkins",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:04",
    },
    {
        "id": 351,
        "password": "pbkdf2_sha256$870000$DlxZlaIr1zADieV0Ics9df$XKZjK6ruTlid+59U/tQuWAFEfrb359ifBGIAsVCckNc=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "debra.tran942@example.com",
        "first_name": "Debra",
        "last_name": "Tran",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:03",
    },
    {
        "id": 341,
        "password": "pbkdf2_sha256$870000$laJU2yk24hYf951ndq1QIY$gI3xN9cD/Eoas3IGNTUEKbVhGZWnuTtVoWu3689ZWg0=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "dillon.thomas701@example.com",
        "first_name": "Dillon",
        "last_name": "Thomas",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:01",
    },
    {
        "id": 331,
        "password": "pbkdf2_sha256$870000$OSG2hir0HJg77UPPeMYkTF$B/5rb0jdKP4UpEdqLiQcccUA/TrfQ0Q/1hr4Uwq2x40=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "donna.frazier17@example.com",
        "first_name": "Donna",
        "last_name": "Frazier",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:59",
    },
    {
        "id": 336,
        "password": "pbkdf2_sha256$870000$VnraTZabr6e8HHjk7jBZkY$C7r05KAS8MtDc6ou1iucoEYVh1ta4y/gMzxKTumvbE0=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "elizabeth.fleming716@example.com",
        "first_name": "Elizabeth",
        "last_name": "Fleming",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:00",
    },
    {
        "id": 352,
        "password": "pbkdf2_sha256$870000$EiGmGeHoJZG8dSDQ1Z9ICN$yTXm7aerU1FuBdu6SFonKwUZGNI7xMYNjJtv//+TmaA=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "elizabeth.morrison931@example.com",
        "first_name": "Elizabeth",
        "last_name": "Morrison",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:03",
    },
    {
        "id": 381,
        "password": "pbkdf2_sha256$870000$rLrsoy6WhbUwATQiDtJJ1z$/aEGxuwPxKy292dRmwN9eYXsibZZB0Fvn+xeHKjtZcc=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "elizabeth.williams941@example.com",
        "first_name": "Elizabeth",
        "last_name": "Williams",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:09",
    },
    {
        "id": 308,
        "password": "pbkdf2_sha256$870000$wtIHtgbZtnt3r2be7FY7hr$o6PUlRKoNmzBECY/SG/reiy3FZ7XcdcotvVT3nG/RGk=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "emily.walters108@example.com",
        "first_name": "Emily",
        "last_name": "Walters",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:54",
    },
    {
        "id": 301,
        "password": "pbkdf2_sha256$870000$RhKm4LpxvhFdQMEFzm8TyL$VVK8CQXbekGNvxCCU10lPMVbn1A8+qotoRqq2Y7603g=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "eric.collins412@example.com",
        "first_name": "Eric",
        "last_name": "Collins",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:51",
    },
    {
        "id": 391,
        "password": "pbkdf2_sha256$870000$YKYRUIb8cNWHANtd0Uf606$80Z4gk3mEv/F8GLyBjM9vFxMqqxYdo4YuLEDHPpoBNo=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "erin.ayala34@example.com",
        "first_name": "Erin",
        "last_name": "Ayala",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:11",
    },
    {
        "id": 306,
        "password": "pbkdf2_sha256$870000$zA1AJjpwO7xcO1bLrzCVfk$LtO4nbxLofCTeexVGBi6xrLDmrfNjbzvhvvhjWOhAio=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "frances.simmons901@example.com",
        "first_name": "Frances",
        "last_name": "Simmons",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:53",
    },
    {
        "id": 343,
        "password": "pbkdf2_sha256$870000$mcfzsETMyMropljxn2tkZL$/5LsXr21x3V1LBVYV9bYgth52tqS6jreVu+O8qT+0Bg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "hr@payroll.com",
        "first_name": "Hr",
        "last_name": "User",
        "is_staff": "1",
        "is_active": "1",
        "is_manager": "1",
        "date_joined": "2025-11-29 18:53:02",
    },
    {
        "id": 376,
        "password": "pbkdf2_sha256$870000$pzoLZBBLBKnwdaEKOfwhs4$1vamuA5CmkOnPP5i0PqrZPH3EETRmHdmwXi/nNOWkLU=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "james.cummings68@example.com",
        "first_name": "James",
        "last_name": "Cummings",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:08",
    },
    {
        "id": 335,
        "password": "pbkdf2_sha256$870000$M4PJYEzxO3evpsru4OcPix$Zed3jY7d8PgRzQvkcgStC/0yinSO1UpR4ADDDL+NqGM=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "james.greene280@example.com",
        "first_name": "James",
        "last_name": "Greene",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:00",
    },
    {
        "id": 322,
        "password": "pbkdf2_sha256$870000$t1WCmxNsiPZei7bRwQIYbe$8pAaRzbmhcavo6Eva9ABYhnjXYYd1/rf8mo4WEeH/yI=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "james.rose768@example.com",
        "first_name": "James",
        "last_name": "Rose",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:57",
    },
    {
        "id": 316,
        "password": "pbkdf2_sha256$870000$gGmvBIT2aDHoouGxTbCzq8$IXOlhjHDu2ZGAxjFmc7b6bxIZzUtKUdk8RA8b7j6t44=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "jamie.black576@example.com",
        "first_name": "Jamie",
        "last_name": "Black",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:56",
    },
    {
        "id": 350,
        "password": "pbkdf2_sha256$870000$9r8kP6T4GQi2dl9FpK1lvr$gbIlRX02r+vRGHONpiRzJE9JRaxx4Lw9CMHUFtrscJs=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "jane.boyle784@example.com",
        "first_name": "Jane",
        "last_name": "Boyle",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:03",
    },
    {
        "id": 388,
        "password": "pbkdf2_sha256$870000$LXK8UxMWc1GAj32SUfQ7KY$BR68jWd6tRPSOHJzdAVThYs/FYioCSRClRWh2LY62vY=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "jason.miller966@example.com",
        "first_name": "Jason",
        "last_name": "Miller",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:11",
    },
    {
        "id": 368,
        "password": "pbkdf2_sha256$870000$nZVBA1ulSHakWi2EYgeXvB$MNsnFqcaHHCN00I7MsS4AnQ/1ZJMt3XsdyYhnXaQLeA=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "javier.anderson70@example.com",
        "first_name": "Javier",
        "last_name": "Anderson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:07",
    },
    {
        "id": 328,
        "password": "pbkdf2_sha256$870000$huhn5K9q5mo6ZSugU7gVLI$idULFiZkBeyMHkFW6p0KmjgTt4GuOnMXUoNFuixNGys=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "jeffrey.anderson863@example.com",
        "first_name": "Jeffrey",
        "last_name": "Anderson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:58",
    },
    {
        "id": 354,
        "password": "pbkdf2_sha256$870000$2PJxxmByXGR3xPheive91A$BJ4A5D4igqU9N5tANoN8Pyr8E+Mz2HAgzS1S6+/XCao=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "jennifer.foster812@example.com",
        "first_name": "Jennifer",
        "last_name": "Foster",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:04",
    },
    {
        "id": 360,
        "password": "pbkdf2_sha256$870000$lqmVrS06ET3OdZPMzLYzbV$b2hO/nFY15yEGVYXYr+soNCkNALVlPmSxKLvTtv2++o=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "jennifer.hall771@example.com",
        "first_name": "Jennifer",
        "last_name": "Hall",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:05",
    },
    {
        "id": 297,
        "password": "pbkdf2_sha256$870000$nKj4s3cGdGXOjuOnfsccy0$xaYIDPb2t1RwnsfTcj20SvNnQqV2D6z0Dv9v2PKJx94=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "jessica.colon200@example.com",
        "first_name": "Jessica",
        "last_name": "Colon",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:50",
    },
    {
        "id": 307,
        "password": "pbkdf2_sha256$870000$hZXcbsEk3iHw5G8XpJfCPf$mSKS+JHai0AZ97HrTAmmLs81nxuvexwG+8iKJM2/9MI=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "joe.miller497@example.com",
        "first_name": "Joe",
        "last_name": "Miller",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:54",
    },
    {
        "id": 383,
        "password": "pbkdf2_sha256$870000$75eOej9G3bLpnKZjM04Jkc$rmzSQBEJlGAm5+/Qkd33HAeQooMeSsTGbSB9XmjlUbc=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "joe.wilson344@example.com",
        "first_name": "Joe",
        "last_name": "Wilson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:10",
    },
    {
        "id": 385,
        "password": "pbkdf2_sha256$870000$ABsqV4SFjeiF1poTIY6O0q$WT22cnJTfTOrzKtktcRRKUK/1hPAnpeGLocYYj+cvP8=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "john.costa821@example.com",
        "first_name": "John",
        "last_name": "Costa",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:10",
    },
    {
        "id": 321,
        "password": "pbkdf2_sha256$870000$HhUgxRzzN2yAgpzg8oSbSd$50RpEp74CX1a62MFDMC3BeipG1gZXDPS8mI4cw3Tpeg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "john.johnson213@example.com",
        "first_name": "John",
        "last_name": "Johnson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:57",
    },
    {
        "id": 317,
        "password": "pbkdf2_sha256$870000$MYXlitD4soiJcf8mwxSzL2$ijL6ULJV4LAW/wI4EA7P03UUCT5X5/o2t2x1r14epuY=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "john.lewis210@example.com",
        "first_name": "John",
        "last_name": "Lewis",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:56",
    },
    {
        "id": 359,
        "password": "pbkdf2_sha256$870000$EsDB4sh63w75L4I4SX4nEr$DTJtpkybk8inFbCcfatYBUsvG5HTEH1pVFqTiEDJnQg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "joseph.bauer103@example.com",
        "first_name": "Joseph",
        "last_name": "Bauer",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:05",
    },
    {
        "id": 380,
        "password": "pbkdf2_sha256$870000$mpfcIAA9RiNvgU3gpx1IKB$cRxwJFTfTkQQQN299Vs/CR69dNr4S3x828FU8y4tEZ8=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "joseph.murphy229@example.com",
        "first_name": "Joseph",
        "last_name": "Murphy",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:09",
    },
    {
        "id": 300,
        "password": "pbkdf2_sha256$870000$XMdPYBTwxi0e3qNg5dfa7H$O0hvOgy16/HMO0zB12pnWNzMfSSKt3VilDx2zKmchOg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "joseph.ortiz707@example.com",
        "first_name": "Joseph",
        "last_name": "Ortiz",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:51",
    },
    {
        "id": 323,
        "password": "pbkdf2_sha256$870000$DPKlYALywaN6blGVzZQ8xc$7Q1LnZc5Q9dlKpqAU1at7uK74etWDQ/TFejyDJtybCU=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "joseph.rodriguez681@example.com",
        "first_name": "Joseph",
        "last_name": "Rodriguez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:57",
    },
    {
        "id": 374,
        "password": "pbkdf2_sha256$870000$il3m6SYueB3Pj978VySzqi$OFYuP2diuWrvhRo1K51xtT4z3QfQe/Wzh7PuoCDe70Y=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "joshua.cohen661@example.com",
        "first_name": "Joshua",
        "last_name": "Cohen",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:08",
    },
    {
        "id": 310,
        "password": "pbkdf2_sha256$870000$brl72PZuF1Sa3hJsFNCYDo$gbDXTultT8o1DmCjxzPbkhkhD9nMTPbgQz431bx5j7Y=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "julie.wilson396@example.com",
        "first_name": "Julie",
        "last_name": "Wilson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:55",
    },
    {
        "id": 339,
        "password": "pbkdf2_sha256$870000$MYUU9oMwtdDDFgEOtqRV7L$qoomZSDjS1UxlWN1z08WCOBryhh5KmDLgy2GJT7Q9HY=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "justin.davenport226@example.com",
        "first_name": "Justin",
        "last_name": "Davenport",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:01",
    },
    {
        "id": 355,
        "password": "pbkdf2_sha256$870000$WqJ9WDQR8ehRhusRA1uRX3$9C++eu7woB9veuyTQ4PvEoUgb+XL02tCNDA2sQ7X6ik=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "kevin.jones846@example.com",
        "first_name": "Kevin",
        "last_name": "Jones",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:04",
    },
    {
        "id": 357,
        "password": "pbkdf2_sha256$870000$0Pq09mYCulcY8iog5bHdwx$3WPsg2qXBorowQoCHkivypzyqWAOBfX/tQmr0qbRhC8=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "laura.sims631@example.com",
        "first_name": "Laura",
        "last_name": "Sims",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:04",
    },
    {
        "id": 302,
        "password": "pbkdf2_sha256$870000$SB24weo1AVeE84uwzjbZkL$YIARjWQdsbouZUYw2KuLEflhv6EOS3ftslRm/IZDGBw=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "lindsay.medina614@example.com",
        "first_name": "Lindsay",
        "last_name": "Medina",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:52",
    },
    {
        "id": 296,
        "password": "pbkdf2_sha256$870000$XY7HEALOMSMDY4w6qcMYrC$zweGm31CrDFrxdYKarlFA1/IxDL7/JN+a32hxABecow=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "louis.stein459@example.com",
        "first_name": "Louis",
        "last_name": "Stein",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:49",
    },
    {
        "id": 295,
        "password": "pbkdf2_sha256$870000$96AiYou7bwIysBpLkcTA5y$aPmwmp4pAhen7jLFCDpz3WoFxKWGOEAsIlWf0j6SK6g=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "luis.davis512@example.com",
        "first_name": "Luis",
        "last_name": "Davis",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:49",
    },
    {
        "id": 356,
        "password": "pbkdf2_sha256$870000$qNUL8CN3I2EHHuNYetd5P9$609teW9H/GNttxFCjGZNEd2uRaWhvNJA56AHKSaWPSg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "madeline.daniel478@example.com",
        "first_name": "Madeline",
        "last_name": "Daniel",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:04",
    },
    {
        "id": 344,
        "password": "pbkdf2_sha256$870000$ONT8lFR1VaIpP3oty3h3gV$rXoKWEDXuk+xmk/n4WpkketGGjRfjnMg7c04njxU4WE=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "manager@payroll.com",
        "first_name": "Manager",
        "last_name": "User",
        "is_staff": "1",
        "is_active": "1",
        "is_manager": "1",
        "date_joined": "2025-11-29 18:53:02",
    },
    {
        "id": 329,
        "password": "pbkdf2_sha256$870000$2Z7rRNU0YVwwPfTkpzsHCL$jevgiHNcOIbj7OJK1Zd8Uqfu3UHdlmLri4pWm3P7tjA=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "marcus.potts315@example.com",
        "first_name": "Marcus",
        "last_name": "Potts",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:59",
    },
    {
        "id": 390,
        "password": "pbkdf2_sha256$870000$PCOjqttcc5tf7AKn83hOIJ$irc3chyxjD2w/oXKGUIqPb6Gatr7LNmsN+9blIKnNL0=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "maria.sampson451@example.com",
        "first_name": "Maria",
        "last_name": "Sampson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:11",
    },
    {
        "id": 363,
        "password": "pbkdf2_sha256$870000$UMITYnjUQh53wJDHDIirvD$dyTCJXqc6+xsXCIz0wPsa5xPAGXa78gpDQxHb0Kqiso=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "mark.harrison573@example.com",
        "first_name": "Mark",
        "last_name": "Harrison",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:06",
    },
    {
        "id": 334,
        "password": "pbkdf2_sha256$870000$JxgUFeDfitCbIhrqI4AdVE$4SasXZew1YjtKakvxbeyWsqvwV1e8t9Yo+a3R8b7cFg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "mark.proctor762@example.com",
        "first_name": "Mark",
        "last_name": "Proctor",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:00",
    },
    {
        "id": 366,
        "password": "pbkdf2_sha256$870000$JRnRfJeSIxm4lP0GJZwC0t$vlOe3eeYE5cIyx0F/Y70cZR64V4M1leR08Ky64inhg0=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "mary.frey620@example.com",
        "first_name": "Mary",
        "last_name": "Frey",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:06",
    },
    {
        "id": 294,
        "password": "pbkdf2_sha256$870000$zCdMaxSHMLIzWcSaNrSaJa$xSzDtslby9WUY4O5YFov+XTW8iBMOnMHbW3MHpca0Sg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "matthew.brewer650@example.com",
        "first_name": "Matthew",
        "last_name": "Brewer",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:48",
    },
    {
        "id": 304,
        "password": "pbkdf2_sha256$870000$GBasqZEZ9v6Qh0vFuLES15$xZt/KMAYwI3GdgGmCHXKw7J4+L1B4YokJOOSzks3RHI=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "melanie.smith787@example.com",
        "first_name": "Melanie",
        "last_name": "Smith",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:53",
    },
    {
        "id": 326,
        "password": "pbkdf2_sha256$870000$6ufIMWGjgFOPH68lKqGbnJ$JmRHiuJjt2iWFy3VVMTIIv363EIVtWlo6J4cF+TCy4E=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "michael.guzman179@example.com",
        "first_name": "Michael",
        "last_name": "Guzman",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:58",
    },
    {
        "id": 312,
        "password": "pbkdf2_sha256$870000$y2GWpjLSp8X3rl7pMaUhil$lYhOQ3t9yldEhPzJSWkjYgUIoZfSlL/lPXfBZ1JnZpM=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "michael.nguyen607@example.com",
        "first_name": "Michael",
        "last_name": "Nguyen",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:55",
    },
    {
        "id": 382,
        "password": "pbkdf2_sha256$870000$RdojpYyRZYlywgSHhafRAE$TlzNwTmqZc5oGU/F3JTQTMhjQwhbXu/bVUkl5gB7r64=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "michael.white552@example.com",
        "first_name": "Michael",
        "last_name": "White",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:10",
    },
    {
        "id": 292,
        "password": "pbkdf2_sha256$870000$Vpy08Cl93qPMYlaiiLtrZT$KLMgttO2xJ7XktlpuZSURQxlS3yO0ZFkHYh8tGyVHUM=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "michelle.drake959@example.com",
        "first_name": "Michelle",
        "last_name": "Drake",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:48",
    },
    {
        "id": 347,
        "password": "pbkdf2_sha256$870000$ugpjyg4eTYbK6DHqFW0gEc$ZyyEl1EyWQamnaDAKj9rjU/Yurlv5T6a+U5UadMqiCU=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "morgan.hardin93@example.com",
        "first_name": "Morgan",
        "last_name": "Hardin",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:02",
    },
    {
        "id": 394,
        "password": "pbkdf2_sha256$870000$84ZbPUJFoln7WsijRmCWxT$bDZR1spQ57Wp2xAQqYGSKUHM5BeYGJClRa53n5qj//Q=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "natalie.cortez939@example.com",
        "first_name": "Natalie",
        "last_name": "Cortez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:12",
    },
    {
        "id": 311,
        "password": "pbkdf2_sha256$870000$kDIIkv3A3lU0gwjmaNMaqa$Nt97RIcYsi2IOiU1vkPykOyM0UFmT5C8zP3YtURViJU=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "natasha.donaldson270@example.com",
        "first_name": "Natasha",
        "last_name": "Donaldson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:55",
    },
    {
        "id": 378,
        "password": "pbkdf2_sha256$870000$TFw5rQleTe7D7zc0GyMlIV$wz8SBfvHoxCnGggri7c9OYQ82bONz9NW3aBeJE1VD2g=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "nichole.soto304@example.com",
        "first_name": "Nichole",
        "last_name": "Soto",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:09",
    },
    {
        "id": 340,
        "password": "pbkdf2_sha256$870000$JM7zdfGtOLx4PNXkcIGDH8$FN/d/ZNsGG30UdAmVYqw1vl1/BF7Kcd5/ZXH9B1Q1L0=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "nicole.white191@example.com",
        "first_name": "Nicole",
        "last_name": "White",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:01",
    },
    {
        "id": 370,
        "password": "pbkdf2_sha256$870000$svIgEgaQMfCK7B7l2QypWE$ILdXRUB65pMEfdy4FYf40R4RmPWpjD3te6q+4EFd0pM=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "paula.sandoval225@example.com",
        "first_name": "Paula",
        "last_name": "Sandoval",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:07",
    },
    {
        "id": 375,
        "password": "pbkdf2_sha256$870000$QLtRNmFuA6uf0waDfIL7bT$9uMaVaNb7QgY80nGRwUKZLcS3r2NFZWM10oS72UhLWs=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "phillip.james838@example.com",
        "first_name": "Phillip",
        "last_name": "James",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:08",
    },
    {
        "id": 384,
        "password": "pbkdf2_sha256$870000$3yN3Xg3MW9Isw0XdEo6NP1$D7srcTvaik0Y3RUBPBmD85Yq6o6Lg4V8SCyR2trywpg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "rachel.myers594@example.com",
        "first_name": "Rachel",
        "last_name": "Myers",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:10",
    },
    {
        "id": 319,
        "password": "pbkdf2_sha256$870000$curL1agfQ5FEkSV9S6kOfk$GNfDyZ91v7xxXddoPbYeZdgCuDKQPeDvpHbrXb8lkEY=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "rebecca.smith118@example.com",
        "first_name": "Rebecca",
        "last_name": "Smith",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:57",
    },
    {
        "id": 365,
        "password": "pbkdf2_sha256$870000$HxmdHUTBQdfB98COcod3Xt$EMzNVWFNx2wnyAQkF6hEkvjuQp7befRDtEIHMKjm/Wg=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "rebekah.williams535@example.com",
        "first_name": "Rebekah",
        "last_name": "Williams",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:06",
    },
    {
        "id": 333,
        "password": "pbkdf2_sha256$870000$Oq1KNQQD3fYautaGPd9mqp$VKD1vqDaudrAm27aMVzqtHmic4zAdv4tn3M8BxTVZrw=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "richard.martin785@example.com",
        "first_name": "Richard",
        "last_name": "Martin",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:59",
    },
    {
        "id": 338,
        "password": "pbkdf2_sha256$870000$QQN74mQ9SaNrN9ArkuyPa4$BdBT0mNKN6HI5TvflvIrlLKwyZYjmGW4uEtKzeoZOMA=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "robert.russell968@example.com",
        "first_name": "Robert",
        "last_name": "Russell",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:01",
    },
    {
        "id": 299,
        "password": "pbkdf2_sha256$870000$OLghwkAftOBXS4vba0VPvJ$vsiH3ZzwqJ+oVDLBztbDtZR1GRJb+uVI7wBV0bi39wk=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "sarah.norris437@example.com",
        "first_name": "Sarah",
        "last_name": "Norris",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:50",
    },
    {
        "id": 318,
        "password": "pbkdf2_sha256$870000$b51auuOydYEChdeI6gICIp$OWfaePBtgJSs+IP8XKaBOcPGglRlWH7S3vQnPkchrZo=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "sarah.richardson266@example.com",
        "first_name": "Sarah",
        "last_name": "Richardson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:56",
    },
    {
        "id": 330,
        "password": "pbkdf2_sha256$870000$oaVAMwgFnNEdmXxOUktdLD$5swHXNtjtm0wKFRG5bzbCM1TDUvZD+M3Dxwljj4SVRU=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "sean.thompson857@example.com",
        "first_name": "Sean",
        "last_name": "Thompson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:59",
    },
    {
        "id": 313,
        "password": "pbkdf2_sha256$870000$KNF6ggxSlhUsqTrnH3Co3B$9aK3LuqCxhsdV0ouJbKeTi6SFuRjGViOiF0Euv8/wQM=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "shannon.cole640@example.com",
        "first_name": "Shannon",
        "last_name": "Cole",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:55",
    },
    {
        "id": 371,
        "password": "pbkdf2_sha256$870000$tmjtR2lnsjKH0ej1dOWPDf$xOQGNo2a2CtZJuUuD7NVO/rHJuJS0av5Jh8KALCOKTw=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "shannon.vazquez39@example.com",
        "first_name": "Shannon",
        "last_name": "Vazquez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:07",
    },
    {
        "id": 389,
        "password": "pbkdf2_sha256$870000$PfKrq8StPw7Ms1gKRdLuhm$M7NnLyY7T2HLHOjCrKBjTf4quGRDIGQa5zgVERbmJIQ=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "sheila.guzman424@example.com",
        "first_name": "Sheila",
        "last_name": "Guzman",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:11",
    },
    {
        "id": 386,
        "password": "pbkdf2_sha256$870000$x9H2pzWFszMaMEOHA4MKCT$kpFSykhnWg3buBs9EMjTPTcF9Gr/CZg5vH6RH2kK+XQ=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "shelby.weber603@example.com",
        "first_name": "Shelby",
        "last_name": "Weber",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:10",
    },
    {
        "id": 309,
        "password": "pbkdf2_sha256$870000$JY6pbCAqikfEFOuRYKis0r$/MWL1e9lIgAqIKCZa+PEKoaKRvd45y1RQanEYIHQEu0=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "stacey.ward416@example.com",
        "first_name": "Stacey",
        "last_name": "Ward",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:52:54",
    },
    {
        "id": 367,
        "password": "pbkdf2_sha256$870000$L7nxyUyYmbDQ4GbMLnG0Uc$sqxkmmi8GdnF8IVw46ewAi5sIHwqPuybh2rlkJIxrGs=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "theodore.tran519@example.com",
        "first_name": "Theodore",
        "last_name": "Tran",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:07",
    },
    {
        "id": 361,
        "password": "pbkdf2_sha256$870000$keoJa53HlYEGX0oB21Rb33$DnK7NN2PpCE6ToOhDE6Gj5lLMNEHm4dlL0e5DutdbGw=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "theresa.dickson133@example.com",
        "first_name": "Theresa",
        "last_name": "Dickson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:05",
    },
    {
        "id": 393,
        "password": "pbkdf2_sha256$870000$sKN15kRjMLbVCby7UjxpU6$1gVml24gczp4FTqd0alCTZH1EwB7OdxX1e1BPOvig9A=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "tiffany.gomez296@example.com",
        "first_name": "Tiffany",
        "last_name": "Gomez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:12",
    },
    {
        "id": 362,
        "password": "pbkdf2_sha256$870000$91GwmO31jmmM0NURNRxhUW$SJKN2azjgIcG14t5995zkeSvXF43aYMF81hNRCgPa/Q=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "tina.ramsey492@example.com",
        "first_name": "Tina",
        "last_name": "Ramsey",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:05",
    },
    {
        "id": 349,
        "password": "pbkdf2_sha256$870000$6elqaLrnHa1cwzmKE1I8lW$W9HdtGnmm8l1kxD/Iss/+n1+OLq7nuewMt6PpVnU0Es=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "todd.adams702@example.com",
        "first_name": "Todd",
        "last_name": "Adams",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:03",
    },
    {
        "id": 337,
        "password": "pbkdf2_sha256$870000$DyDKYvLKuh1K1tuA4s4C3i$zc7C7iMSJOWKbrYsk8tXIzHPKiGFIX+DpO/5dwjJDAo=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "victoria.fernandez497@example.com",
        "first_name": "Victoria",
        "last_name": "Fernandez",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:00",
    },
    {
        "id": 373,
        "password": "pbkdf2_sha256$870000$49Cme9tFThej9W2oWlGvr8$lkX0cK2E0zUkm6XI35wF4+wDEB/W/w26EDm2n9b66uo=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "william.edwards967@example.com",
        "first_name": "William",
        "last_name": "Edwards",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:08",
    },
    {
        "id": 364,
        "password": "pbkdf2_sha256$870000$Dzqi6dUhf2ueiF4wjsiq6O$JBPX8p3sQhrsm+ot0TLPH/GPI3Ggi7iM8zUFZ8LyK+8=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "william.jackson927@example.com",
        "first_name": "William",
        "last_name": "Jackson",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:06",
    },
    {
        "id": 372,
        "password": "pbkdf2_sha256$870000$QqwsrH5lQN7gr1qQrH6zxW$o0/bnUgoZ0iAWx9TWxElz/ijHYjgBOIpJKfzMFfpgGs=",
        "last_login": "",
        "is_superuser": "0",
        "groups": "",
        "user_permissions": "",
        "email": "william.white760@example.com",
        "first_name": "William",
        "last_name": "White",
        "is_staff": "0",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-29 18:53:08",
    },
    {
        "id": 1,
        "password": "pbkdf2_sha256$870000$j6r7YnKQWRDkV4kr1JSani$DOOeADQreJgC8VAAWZtU40zCiCQ5gBvg8zC86FJIr/M=",
        "last_login": "2025-11-28 18:01:30",
        "is_superuser": "1",
        "groups": "",
        "user_permissions": "",
        "email": "zayyad@example.com",
        "first_name": "",
        "last_name": "",
        "is_staff": "1",
        "is_active": "1",
        "is_manager": "0",
        "date_joined": "2025-11-28 18:00:26",
    },
]

# Track used numbers to ensure uniqueness
_used_emp_numbers = set()
_used_nin_numbers = set()
_used_tin_numbers = set()
_used_bank_accounts = set()


def generate_emp_id():
    max_attempts = 1000
    for _ in range(max_attempts):
        number = random.randint(0, 9999)
        emp_id_value = f"EMP-{number}-2025"
        if emp_id_value not in _used_emp_numbers:
            _used_emp_numbers.add(emp_id_value)
            return emp_id_value
    # Fallback if we can't find a unique number
    return f"EMP-{len(_used_emp_numbers)}-2025"


def generate_nin_no():
    max_attempts = 1000
    for _ in range(max_attempts):
        num = random.randint(11111111111, 99999999999)
        nin_value = f"NG-{num}"
        if nin_value not in _used_nin_numbers:
            _used_nin_numbers.add(nin_value)
            return nin_value
    # Fallback if we can't find a unique number
    return f"NG-{11111111111 + len(_used_nin_numbers)}"


def generate_tin_no():
    max_attempts = 1000
    for _ in range(max_attempts):
        num = random.randint(11111111111, 99999999999)
        tin_value = f"TIN-{num}"
        if tin_value not in _used_tin_numbers:
            _used_tin_numbers.add(tin_value)
            return tin_value
    # Fallback if we can't find a unique number
    return f"TIN-{11111111111 + len(_used_tin_numbers)}"


def generate_bank_account():
    max_attempts = 1000
    for _ in range(max_attempts):
        num = random.randint(1000000000, 9999999999)
        account_value = str(num)
        if account_value not in _used_bank_accounts:
            _used_bank_accounts.add(account_value)
            return account_value
    # Fallback if we can't find a unique number
    return str(1000000000 + len(_used_bank_accounts))


def generate_random_date():
    year = random.randint(1970, 2000)
    month = random.randint(1, 12)
    return f"{year}-{month:02d}-01"


def generate_phone_number():
    # Generate a random US-style phone number
    area_code = random.randint(200, 999)
    prefix = random.randint(200, 999)
    line_number = random.randint(1000, 9999)
    return f"({area_code}) {prefix}-{line_number}"


def get_random_gender():
    genders = ["male", "female", "others"]
    return random.choice(genders)


def get_random_contract_type():
    contract_types = ["P", "T"]  # Permanent, Temporary
    return random.choice(contract_types)


def get_random_job_title():
    job_titles = [
        "C",
        "JS",
        "OP",
        "SU",
        "M",
        "COO",
    ]  # Casual, Junior staff, Operator, Supervisor, Manager, C.O.O
    return random.choice(job_titles)


def get_random_bank():
    banks = ["Zenith", "Access", "GTB", "Jaiz", "FCMB", "FBN", "Union", "UBA"]
    return random.choice(banks)


# Map department names to IDs (these would need to match the actual IDs in your database)
# For now, we'll use a simple mapping that assumes departments are created with sequential IDs
DEPARTMENT_MAPPING = {
    "Engineering": 25,  # Human Resources
    "Human Resources": 26,  # Finance
    "Finance": 27,  # Information Technology
    "Marketing": 28,  # Marketing
    "Operations": 29,  # Customer Service
    "Customer Service": 30,  # Administration
    "Administration": 31,  # Research & Development
    "Research & Development": 32,
}

""" 
25	"Engineering"
26	"Human Resources"
27	"Finance"
28	"Marketing"
29	"Operations"
30	"Customer Service"
31	"Administration"
32	"Research & Development"

"""


def get_department_id():
    """Return a random department ID"""
    department_ids = list(DEPARTMENT_MAPPING.values())
    return random.choice(department_ids)


def get_department_name():
    """Return a random department name"""
    department_names = list(DEPARTMENT_MAPPING.keys())
    return random.choice(department_names)


def get_random_status():
    statuses = ["active", "pending"]
    return random.choice(statuses)


def generate_employee_profiles():
    """
    Generates a list of employee profile dictionaries from users_data.
    """
    employee_profiles = []

    for user in users_data:
        # Skip users with empty first and last names
        if not user["first_name"] and not user["last_name"]:
            continue

        # Generate slug from first and last name
        first_name = user["first_name"] or ""
        last_name = user["last_name"] or ""
        slug = f"{first_name.lower()}-{last_name.lower()}".replace(" ", "-")

        # Determine job title based on role
        if user.get("is_manager") == "1":
            job_title = "M"  # Manager
        elif user.get("is_staff") == "1":
            job_title = random.choice(
                ["SU", "OP", "JS"]
            )  # Supervisor, Operator, Junior staff
        else:
            job_title = random.choice(
                ["C", "JS", "OP"]
            )  # Casual, Junior staff, Operator

        # Create employee profile dictionary
        profile = {
            "id": user["id"],
            "emp_id": generate_emp_id(),
            "slug": slug,
            "department": get_department_id(),
            "user": user["id"],
            "first_name": user["first_name"],
            "last_name": user["last_name"],
            "email": user["email"],
            "employee_pay": random.randint(1, 100),
            "photo": "default.png",
            "nin": generate_nin_no(),
            "tin_no": generate_tin_no(),
            "pension_rsa": f"RSA-{random.randint(1000000000, 9999999999)}",
            "date_of_birth": generate_random_date(),
            "date_of_employment": generate_random_date(),
            "contract_type": get_random_contract_type(),
            "phone": generate_phone_number(),
            "gender": get_random_gender(),
            "address": f"{random.randint(100, 999)} Main St, City, State {random.randint(10000, 99999)}",
            "emergency_contact_name": f"{random.choice(['John', 'Jane', 'Robert', 'Mary'])} {random.choice(['Smith', 'Johnson', 'Williams', 'Brown'])}",
            "emergency_contact_relationship": random.choice(
                ["Spouse", "Parent", "Sibling", "Friend"]
            ),
            "emergency_contact_phone": generate_phone_number(),
            "next_of_kin_name": f"{random.choice(['John', 'Jane', 'Robert', 'Mary'])} {random.choice(['Smith', 'Johnson', 'Williams', 'Brown'])}",
            "next_of_kin_relationship": random.choice(
                ["Spouse", "Parent", "Sibling", "Child"]
            ),
            "next_of_kin_phone": generate_phone_number(),
            "job_title": job_title,
            "bank": get_random_bank(),
            "bank_account_name": f"{user['first_name']} {user['last_name']}",
            "bank_account_number": generate_bank_account(),
            "net_pay": "0.00",
            "status": "active" if user.get("is_active") == "1" else "pending",
        }

        employee_profiles.append(profile)

    return employee_profiles


if __name__ == "__main__":
    profiles = generate_employee_profiles()

    # Save to JSON file
    with open("employee_profiles.json", "w") as f:
        json.dump(profiles, f, indent=2)

    print(
        f"Generated {len(profiles)} employee profiles and saved to employee_profiles.json"
    )
