# Generated by Django 5.1.5 on 2026-05-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_disciplinary_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='disciplinarycase',
            new_name='accounting__case_nu_56f812_idx',
            old_name='acct_disc_case_idx',
        ),
        migrations.RenameIndex(
            model_name='disciplinarycase',
            new_name='accounting__status_8e20af_idx',
            old_name='acct_disc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='disciplinarycase',
            new_name='accounting__violati_445bdd_idx',
            old_name='acct_disc_level_idx',
        ),
        migrations.RenameIndex(
            model_name='disciplinarycase',
            new_name='accounting__require_49ca31_idx',
            old_name='acct_disc_review_idx',
        ),
    ]
