# Generated by Django 5.1.5 on 2026-05-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tenant_scope_accounting'),
        ('company', '0003_backfill_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=40)),
                ('report_type', models.CharField(choices=[('PROFIT_LOSS', 'Profit and Loss'), ('BALANCE_SHEET', 'Balance Sheet'), ('CUSTOM', 'Custom Report')], default='PROFIT_LOSS', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report_definitions', to='company.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('line_number', models.PositiveIntegerField()),
                ('row_code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=255)),
                ('line_type', models.CharField(choices=[('HEADING', 'Heading'), ('ACCOUNT_SUM', 'Account Sum')], default='ACCOUNT_SUM', max_length=20)),
                ('invert_sign', models.BooleanField(default=False, help_text='Display this line as the opposite sign for contribution-style reports.')),
                ('show_zero', models.BooleanField(default=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='financial_report_lines', to='accounting.account')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.financialreportdefinition')),
            ],
            options={
                'ordering': ['line_number', 'row_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialreportdefinition',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_financial_report_company_code'),
        ),
        migrations.AddConstraint(
            model_name='financialreportline',
            constraint=models.UniqueConstraint(fields=('report', 'line_number'), name='uniq_financial_report_line_number'),
        ),
        migrations.AddConstraint(
            model_name='financialreportline',
            constraint=models.UniqueConstraint(fields=('report', 'row_code'), name='uniq_financial_report_row_code'),
        ),
    ]
