# Generated by Django 5.1.5 on 2026-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_financialreportdefinition_financialreportline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportline',
            name='formula',
            field=models.CharField(blank=True, help_text='Use row codes with + and - operators, for example REV-COGS.', max_length=255),
        ),
        migrations.AlterField(
            model_name='financialreportline',
            name='line_type',
            field=models.CharField(choices=[('HEADING', 'Heading'), ('ACCOUNT_SUM', 'Account Sum'), ('FORMULA', 'Formula')], default='ACCOUNT_SUM', max_length=20),
        ),
    ]
