# Generated by Django 5.1.5 on 2026-05-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_account_account_segment_code_account_currency_and_more'),
        ('company', '0003_backfill_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingaudittrail',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('REVERSE', 'Reverse'), ('CLOSE_PERIOD', 'Close Period'), ('CLOSE_FISCAL_YEAR', 'Close Fiscal Year'), ('FX_REVALUATION', 'FX Revaluation'), ('FX_REVALUATION_REVERSE', 'FX Revaluation Reverse')], max_length=25),
        ),
        migrations.CreateModel(
            name='CurrencyRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('revaluation_date', models.DateField()),
                ('base_currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('memo', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_revaluations', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revaluations', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_revaluations', to='accounting.journal')),
            ],
            options={
                'ordering': ['-revaluation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRevaluationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('foreign_currency', models.CharField(max_length=3)),
                ('balance_fc', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_at_original', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_at_revaluation', models.DecimalField(decimal_places=8, max_digits=18)),
                ('base_value_original', models.DecimalField(decimal_places=2, max_digits=18)),
                ('base_value_revalued', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unrealized_gain_loss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluation_lines', to='accounting.account')),
                ('revaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.currencyrevaluation')),
            ],
            options={
                'ordering': ['account__account_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='currencyrevaluation',
            constraint=models.UniqueConstraint(fields=('company', 'revaluation_date', 'base_currency'), name='uniq_reval_company_date_currency'),
        ),
    ]
