# Generated by Django 5.1.5 on 2026-05-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_add_currency_revaluation'),
        ('company', '0003_backfill_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreconciliation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('is_matched', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='company.company')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='accounting.accountreconciliation')),
            ],
            options={
                'ordering': ['transaction_date', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_matched', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED_BANK', 'Unmatched (Bank)'), ('UNMATCHED_LEDGER', 'Unmatched (Ledger)')], default='MATCHED', max_length=20)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='accounting.banktransaction')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='accounting.journalentry')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.accountreconciliation')),
            ],
            options={
                'ordering': ['bank_transaction__transaction_date'],
            },
        ),
    ]
