# Generated by Django 5.1.5 on 2026-05-29 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_add_bank_reconciliation'),
        ('company', '0003_backfill_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('report_type', models.CharField(choices=[('TRIAL_BALANCE', 'Trial Balance'), ('BALANCE_SHEET', 'Balance Sheet'), ('INCOME_STATEMENT', 'Income Statement'), ('GENERAL_LEDGER', 'General Ledger')], max_length=30)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('output_file', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report_jobs', to='company.company')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to='accounting.accountingperiod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='accounting__company_59afc0_idx'), models.Index(fields=['status', 'queued_at'], name='accounting__status_192116_idx')],
            },
        ),
    ]
