# Generated by Django 5.1.5 on 2026-05-29 13:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_add_financial_report_job'),
        ('company', '0003_backfill_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_type', models.CharField(choices=[('VAT', 'Value Added Tax'), ('WHT', 'Withholding Tax'), ('PAYE', 'PAYE Income Tax'), ('PENSION', 'Pension Contribution')], max_length=20)),
                ('jurisdiction_code', models.CharField(default='NG-FIRS', max_length=40)),
                ('return_period_start', models.DateField()),
                ('return_period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FILED', 'Filed'), ('AMENDED', 'Amended')], default='DRAFT', max_length=20)),
                ('total_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_input_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('filing_reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to='company.company')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_tax_returns', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_returns', to='accounting.accountingperiod')),
            ],
            options={
                'ordering': ['-return_period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_return_lines', to='accounting.account')),
                ('tax_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_return_tax_lines', to='accounting.account')),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.taxreturn')),
            ],
            options={
                'ordering': ['account__account_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxreturn',
            constraint=models.UniqueConstraint(fields=('company', 'return_type', 'return_period_start', 'return_period_end'), name='uniq_tax_return_company_type_period'),
        ),
    ]
