# Generated by Django 5.1.5 on 2026-05-29 19:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_add_tax_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='postingrule',
            name='document_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALES_INVOICE', 'Sales Invoice'), ('CUSTOMER_RETURN', 'Customer Return'), ('SUPPLIER_RETURN', 'Supplier Return'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('TAX_REMITTANCE', 'Tax Remittance'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('STOCK_COUNT', 'Stock Count'), ('SALES_ORDER', 'Sales Order'), ('VENDOR_BILL', 'Vendor Bill'), ('LANDED_COST', 'Landed Cost'), ('SHIPMENT', 'Shipment')], max_length=30),
        ),
    ]
