# Generated by Django 5.1.5 on 2026-05-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_add_account_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
