# Generated by Django 5.1.5 on 2026-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_journalentry_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreconciliation',
            name='ledger_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountreconciliation',
            name='statement_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountreconciliation',
            name='variance',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='accrualtemplate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='reconciliationitem',
            name='amount_matched',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
