# Generated by Codex on 2026-06-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_alter_accountreconciliation_ledger_balance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplinaryCaseAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("investigation_started", "Investigation Started"),
                            ("decision_recorded", "Decision Recorded"),
                            ("sanction_created", "Sanction Created"),
                            ("sanction_completed", "Sanction Completed"),
                            ("appeal_submitted", "Appeal Submitted"),
                            ("appeal_reviewed", "Appeal Reviewed"),
                            ("status_changed", "Status Changed"),
                            ("case_closed", "Case Closed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disciplinary_case_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="accounting.disciplinarycase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplinary Case Audit Event",
                "verbose_name_plural": "Disciplinary Case Audit Events",
                "ordering": ["-timestamp", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="disciplinarycaseaudit",
            index=models.Index(
                fields=["case", "timestamp"],
                name="accounting__case_id_8f8763_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinarycaseaudit",
            index=models.Index(
                fields=["actor", "timestamp"],
                name="accounting__actor_i_57f537_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinarycaseaudit",
            index=models.Index(
                fields=["action", "timestamp"],
                name="accounting__action_6464b1_idx",
            ),
        ),
    ]
