# Generated by Django 5.1.5 on 2026-08-14 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_journalattachment_recurringjournaltemplate"),
        ("company", "0003_backfill_memberships"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinarycase",
            name="case_number",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="journal",
            name="transaction_number",
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name="disciplinarycase",
            constraint=models.UniqueConstraint(
                fields=("company", "case_number"), name="uniq_case_company_case_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="journal",
            constraint=models.UniqueConstraint(
                fields=("company", "transaction_number"),
                name="uniq_journal_company_transaction_number",
            ),
        ),
    ]
