# Generated by Django 5.1.15 on 2026-09-26 10:47
# Backfills tenant company on legacy audit rows before enforcing NOT NULL.

import django.db.models.deletion
from django.db import migrations, models


def backfill_audit_company(apps, schema_editor):
    AccountingAuditTrail = apps.get_model("accounting", "AccountingAuditTrail")
    JournalEntry = apps.get_model("accounting", "JournalEntry")
    Journal = apps.get_model("accounting", "Journal")
    Account = apps.get_model("accounting", "Account")
    Company = apps.get_model("company", "Company")
    User = apps.get_model("users", "CustomUser")
    ContentType = apps.get_model("contenttypes", "ContentType")

    default_company = Company.objects.order_by("id").first()
    if default_company is None:
        return

    try:
        entry_ct = ContentType.objects.get(app_label="accounting", model="journalentry")
    except ContentType.DoesNotExist:
        entry_ct = None

    nulls = AccountingAuditTrail.objects.filter(company__isnull=True).only(
        "id", "content_type_id", "object_id", "user_id"
    )
    for row in nulls.iterator(chunk_size=500):
        company_id = None
        if entry_ct is not None and row.content_type_id == entry_ct.id:
            je = JournalEntry.objects.filter(pk=row.object_id).values(
                "journal__company_id", "account__company_id"
            ).first()
            if je:
                company_id = je["journal__company_id"] or je["account__company_id"]
        if company_id is None and row.user_id:
            user = User.objects.filter(pk=row.user_id).values(
                "active_company_id", "company_id"
            ).first()
            if user:
                company_id = user["active_company_id"] or user["company_id"]
        if company_id is None:
            company_id = default_company.id
        AccountingAuditTrail.objects.filter(pk=row.pk).update(company_id=company_id)


def backfill_disciplinary_company(apps, schema_editor):
    DisciplinaryCase = apps.get_model("accounting", "DisciplinaryCase")
    Company = apps.get_model("company", "Company")
    default_company = Company.objects.order_by("id").first()
    if default_company is None:
        return
    DisciplinaryCase.objects.filter(company__isnull=True).update(
        company_id=default_company.id
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_disciplinarycase_case_number_and_more'),
        ('company', '0003_backfill_memberships'),
    ]

    operations = [
        migrations.RunPython(
            backfill_audit_company, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            backfill_disciplinary_company, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='accountingaudittrail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_audit_trails', to='company.company'),
        ),
        migrations.AlterField(
            model_name='disciplinarycase',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_cases', to='company.company'),
        ),
    ]
